#!/usr/bin/env python3
"""Generate the rio calibration yaml for our platform (baselines/configs/).

Our extrinsics (analysis/config/extrinsics.yaml, locked pitch from the
2026-06-12 sweeps): R_body<-radar = Rz(yaw) Ry(pitch) Rx(roll) with
[roll,pitch,yaw] = [180, 27.5, 0] deg (ZYX, see
analysis/lib/radar_velocity_utils.py rotation_matrix_from_euler).

rio's pcl2msgToPcl remaps TI clouds x'=-y, y'=x (TI x-forward ->
rio x-right / y-forward / z-up), i.e. v_rio = Rz(+90deg) v_ours.
So the calib quaternion handed to rio must be
  R_b_r(rio) = R_b_r(ours) . Rz(-90deg)
"""
from pathlib import Path

import numpy as np
from scipy.spatial.transform import Rotation as R

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / 'baselines/configs/calib_our_platform.yaml'

# Locked-pitch extrinsics used by all current solver configs (CLAUDE.md):
ROLL, PITCH, YAW = 180.0, 27.5, 0.0          # deg, ZYX (yaw.pitch.roll)
L_B_R = [0.08, 0.02, -0.01]                  # m, body frame

R_b_r_ours = R.from_euler('ZYX', [YAW, PITCH, ROLL], degrees=True)
R_b_r_rio = R_b_r_ours * R.from_euler('z', -90, degrees=True)
qx, qy, qz, qw = R_b_r_rio.as_quat()

# sanity: rio radar y axis (boresight) must map near body +x (pitch down 27.5)
boresight_body = R_b_r_rio.apply([0, 1, 0])
exp = [np.cos(np.radians(PITCH)), 0, -np.sin(np.radians(PITCH))]
assert np.allclose(boresight_body, exp, atol=1e-9), boresight_body

OUT.write_text(f"""## Topics (as written by baselines/adapters/convert_bag_to_rio.py)
topic_imu: "/sensor_platform/imu"
topic_baro_altimeter: "/sensor_platform/baro"
topic_radar_scan: "/sensor_platform/radar/scan"
topic_radar_trigger: "/sensor_platform/radar/trigger"
topic_ground_truth_pose: "/ground_truth/pose"
topic_ground_truth_twist: "/ground_truth/twist"
topic_ground_truth_twist_body: "/ground_truth/twist_body"

## Extrinsic calibration of body frame to radar frame
# translation of radar frame expressed in body frame
# (= our analysis/config/extrinsics.yaml translation_body_m)
l_b_r_x: {L_B_R[0]}
l_b_r_y: {L_B_R[1]}
l_b_r_z: {L_B_R[2]}

# rotation radar frame to body frame:
# R_b_r(ours, euler ZYX [{YAW},{PITCH},{ROLL}] deg) . Rz(-90deg)
# The Rz(-90) compensates rio's internal TI-cloud remap (x'=-y, y'=x);
# generated by baselines/adapters/gen_rio_calib.py
q_b_r_w: {qw:.9f}
q_b_r_x: {qx:.9f}
q_b_r_y: {qy:.9f}
q_b_r_z: {qz:.9f}

# length of each radar frame (="exposure time" of radar scan) in milliseconds
# IWR6843 best_velocity cfg: active chirping window per frame
radar_frame_ms: 18.5

# nominal radar rate of our bags (589 msgs / 59 s)
radar_rate: 10
""")
print(f'wrote {OUT}')
print('q_b_r (w,x,y,z) =', np.round([qw, qx, qy, qz], 6))
print('boresight in body =', np.round(boresight_body, 6))
