# (start_offset_sec, duration_sec) for each named flight window
circle:                               [25.5, 8.5]
circle_fast:                          [14.5, 8.5]
circle_fwd:                           [28.0, 8.0]
loopings:                             [9.5,  8.5]
backflips:                            [26.5, 5.0]
backflips_best_velocity:              [15.6, 10.0]
circle_best_velocity:                 [22.2, 8.4]
fast_racing_1_velocity_no_clustering: [16.9, 18.1]
fast_racing_best_velocity:            [19.1, 18.0]
slow_racing_best_velocity:            [19.1, 25.8]
