// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

#include <sym/rot3.h>

namespace sym {

/**
 * Radar Doppler residual for C++ analytic-Jacobian generation.
 *
 * u_body is the pre-rotated bearing (R_radar_to_body * u_sensor), treated as
 * a constant parameter so R_body_sensor does not appear in the generated code.
 * Jacobians are generated w.r.t. v_world (index 0), R_bw (index 1), omega (index 2).
 *     res_D_v_world: (1x3) jacobian of res (1) wrt arg v_world (3)
 *     res_D_R_bw: (1x3) jacobian of res (1) wrt arg R_bw (3)
 *     res_D_omega: (1x3) jacobian of res (1) wrt arg omega (3)
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 1, 1> RadarSensorJacWithJacobians012(
    const Eigen::Matrix<Scalar, 3, 1>& v_world, const sym::Rot3<Scalar>& R_bw,
    const Eigen::Matrix<Scalar, 3, 1>& omega, const Eigen::Matrix<Scalar, 3, 1>& u_body,
    const Eigen::Matrix<Scalar, 3, 1>& t, const Scalar v_meas, const Scalar epsilon,
    Eigen::Matrix<Scalar, 1, 3>* const res_D_v_world = nullptr,
    Eigen::Matrix<Scalar, 1, 3>* const res_D_R_bw = nullptr,
    Eigen::Matrix<Scalar, 1, 3>* const res_D_omega = nullptr) {
  // Total ops: 146

  // Unused inputs
  (void)epsilon;

  // Input arrays
  const Eigen::Matrix<Scalar, 4, 1>& _R_bw = R_bw.Data();

  // Intermediate terms (41)
  const Scalar _tmp0 = std::pow(_R_bw[2], Scalar(2));
  const Scalar _tmp1 = -2 * _tmp0;
  const Scalar _tmp2 = std::pow(_R_bw[1], Scalar(2));
  const Scalar _tmp3 = 1 - 2 * _tmp2;
  const Scalar _tmp4 = _tmp1 + _tmp3;
  const Scalar _tmp5 = 2 * _R_bw[1];
  const Scalar _tmp6 = _R_bw[0] * _tmp5;
  const Scalar _tmp7 = 2 * _R_bw[2] * _R_bw[3];
  const Scalar _tmp8 = _tmp6 + _tmp7;
  const Scalar _tmp9 = 2 * _R_bw[0];
  const Scalar _tmp10 = _R_bw[2] * _tmp9;
  const Scalar _tmp11 = _R_bw[3] * _tmp5;
  const Scalar _tmp12 = -_tmp11;
  const Scalar _tmp13 = _tmp10 + _tmp12;
  const Scalar _tmp14 = _tmp13 * v_world(2, 0) + _tmp8 * v_world(1, 0);
  const Scalar _tmp15 = std::pow(_R_bw[0], Scalar(2));
  const Scalar _tmp16 = -2 * _tmp15;
  const Scalar _tmp17 = _tmp16 + _tmp3;
  const Scalar _tmp18 = _R_bw[2] * _tmp5;
  const Scalar _tmp19 = _R_bw[3] * _tmp9;
  const Scalar _tmp20 = -_tmp19;
  const Scalar _tmp21 = _tmp18 + _tmp20;
  const Scalar _tmp22 = _tmp10 + _tmp11;
  const Scalar _tmp23 = _tmp21 * v_world(1, 0) + _tmp22 * v_world(0, 0);
  const Scalar _tmp24 = _tmp1 + _tmp16 + 1;
  const Scalar _tmp25 = -_tmp7;
  const Scalar _tmp26 = _tmp25 + _tmp6;
  const Scalar _tmp27 = _tmp18 + _tmp19;
  const Scalar _tmp28 = _tmp26 * v_world(0, 0) + _tmp27 * v_world(2, 0);
  const Scalar _tmp29 = -_tmp2;
  const Scalar _tmp30 = _tmp0 + _tmp29;
  const Scalar _tmp31 = -_tmp15;
  const Scalar _tmp32 = std::pow(_R_bw[3], Scalar(2));
  const Scalar _tmp33 = _tmp31 + _tmp32;
  const Scalar _tmp34 = -_tmp32;
  const Scalar _tmp35 = _tmp15 + _tmp34;
  const Scalar _tmp36 = -_tmp6;
  const Scalar _tmp37 = -_tmp18;
  const Scalar _tmp38 = -_tmp0;
  const Scalar _tmp39 = _tmp2 + _tmp38;
  const Scalar _tmp40 = -_tmp10;

  // Output terms (4)
  Eigen::Matrix<Scalar, 1, 1> _res;

  _res(0, 0) =
      u_body(0, 0) *
          (_tmp14 + _tmp4 * v_world(0, 0) + omega(1, 0) * t(2, 0) - omega(2, 0) * t(1, 0)) +
      u_body(1, 0) *
          (_tmp24 * v_world(1, 0) + _tmp28 - omega(0, 0) * t(2, 0) + omega(2, 0) * t(0, 0)) +
      u_body(2, 0) *
          (_tmp17 * v_world(2, 0) + _tmp23 + omega(0, 0) * t(1, 0) - omega(1, 0) * t(0, 0)) +
      v_meas;

  if (res_D_v_world != nullptr) {
    Eigen::Matrix<Scalar, 1, 3>& _res_D_v_world = (*res_D_v_world);

    _res_D_v_world(0, 0) = _tmp22 * u_body(2, 0) + _tmp26 * u_body(1, 0) + _tmp4 * u_body(0, 0);
    _res_D_v_world(0, 1) = _tmp21 * u_body(2, 0) + _tmp24 * u_body(1, 0) + _tmp8 * u_body(0, 0);
    _res_D_v_world(0, 2) = _tmp13 * u_body(0, 0) + _tmp17 * u_body(2, 0) + _tmp27 * u_body(1, 0);
  }

  if (res_D_R_bw != nullptr) {
    Eigen::Matrix<Scalar, 1, 3>& _res_D_R_bw = (*res_D_R_bw);

    _res_D_R_bw(0, 0) =
        u_body(1, 0) * (_tmp23 + v_world(2, 0) * (_tmp30 + _tmp33)) +
        u_body(2, 0) * (v_world(0, 0) * (_tmp36 + _tmp7) + v_world(1, 0) * (_tmp30 + _tmp35) +
                        v_world(2, 0) * (_tmp20 + _tmp37));
    _res_D_R_bw(0, 1) =
        u_body(0, 0) * (v_world(0, 0) * (_tmp12 + _tmp40) + v_world(1, 0) * (_tmp19 + _tmp37) +
                        v_world(2, 0) * (_tmp35 + _tmp39)) +
        u_body(2, 0) * (_tmp14 + v_world(0, 0) * (_tmp15 + _tmp29 + _tmp32 + _tmp38));
    _res_D_R_bw(0, 2) =
        u_body(0, 0) * (_tmp28 + v_world(1, 0) * (_tmp33 + _tmp39)) +
        u_body(1, 0) * (v_world(0, 0) * (_tmp0 + _tmp2 + _tmp31 + _tmp34) +
                        v_world(1, 0) * (_tmp25 + _tmp36) + v_world(2, 0) * (_tmp11 + _tmp40));
  }

  if (res_D_omega != nullptr) {
    Eigen::Matrix<Scalar, 1, 3>& _res_D_omega = (*res_D_omega);

    _res_D_omega(0, 0) = t(1, 0) * u_body(2, 0) - t(2, 0) * u_body(1, 0);
    _res_D_omega(0, 1) = -t(0, 0) * u_body(2, 0) + t(2, 0) * u_body(0, 0);
    _res_D_omega(0, 2) = t(0, 0) * u_body(1, 0) - t(1, 0) * u_body(0, 0);
  }

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
