"""
Auto-generated analytical Jacobians for radar-inertial odometry.

Generated by: derive_jacobians_symforce.py (using SymForce 0.10.1)
This file has NO dependency on SymForce — it uses only numpy and math.

Contains:
- radar_residual_with_jacobians(): Doppler residual + Jacobians w.r.t. v_world, delta, omega
- accel_residual_with_jacobians(): Accel residual + Jacobians w.r.t. a_world, delta, b_a
- gyro_residual_with_jacobians():  Gyro residual  + Jacobians w.r.t. delta, delta_dot, b_g
- Rot3: Lightweight quaternion wrapper matching SymForce convention [x, y, z, w]

Usage:
    from generated_jacobians import (
        radar_residual_with_jacobians,
        accel_residual_with_jacobians,
        gyro_residual_with_jacobians,
        Rot3,
    )

    R_nom = Rot3(quat_xyzw)
    R_bs = Rot3(quat_xyzw)
    res, J_v, J_delta, J_omega = radar_residual_with_jacobians(
        v_world, R_nom, delta, omega, u_sensor, t_body_sensor, R_bs, v_meas, epsilon
    )
"""

import math
import typing as T
import numpy


class Rot3:
    """
    Lightweight quaternion wrapper matching SymForce Rot3 interface.

    Stores quaternion as [x, y, z, w] (Hamilton convention).
    Only provides the .data property needed by generated code.
    """
    __slots__ = ['data']

    def __init__(self, quat_xyzw):
        """
        Args:
            quat_xyzw: Quaternion as [x, y, z, w] array or list.
        """
        if hasattr(quat_xyzw, 'tolist'):
            self.data = quat_xyzw.tolist()
        else:
            self.data = list(quat_xyzw)

    @staticmethod
    def from_rotation_matrix(R):
        """
        Create Rot3 from a 3x3 rotation matrix.

        Uses Shepperd's method for numerical stability.
        Returns quaternion in [x, y, z, w] format.
        """
        trace = R[0, 0] + R[1, 1] + R[2, 2]
        if trace > 0:
            s = 0.5 / math.sqrt(trace + 1.0)
            w = 0.25 / s
            x = (R[2, 1] - R[1, 2]) * s
            y = (R[0, 2] - R[2, 0]) * s
            z = (R[1, 0] - R[0, 1]) * s
        elif R[0, 0] > R[1, 1] and R[0, 0] > R[2, 2]:
            s = 2.0 * math.sqrt(1.0 + R[0, 0] - R[1, 1] - R[2, 2])
            w = (R[2, 1] - R[1, 2]) / s
            x = 0.25 * s
            y = (R[0, 1] + R[1, 0]) / s
            z = (R[0, 2] + R[2, 0]) / s
        elif R[1, 1] > R[2, 2]:
            s = 2.0 * math.sqrt(1.0 + R[1, 1] - R[0, 0] - R[2, 2])
            w = (R[0, 2] - R[2, 0]) / s
            x = (R[0, 1] + R[1, 0]) / s
            y = 0.25 * s
            z = (R[1, 2] + R[2, 1]) / s
        else:
            s = 2.0 * math.sqrt(1.0 + R[2, 2] - R[0, 0] - R[1, 1])
            w = (R[1, 0] - R[0, 1]) / s
            x = (R[0, 2] + R[2, 0]) / s
            y = (R[1, 2] + R[2, 1]) / s
            z = 0.25 * s

        # Normalize
        norm = math.sqrt(x*x + y*y + z*z + w*w)
        return Rot3([x/norm, y/norm, z/norm, w/norm])



# ======================================================================
# RADAR DOPPLER RESIDUAL + JACOBIANS
# ======================================================================


# --- From: radar_residual_with_jacobians0236.py ---

def radar_residual_with_jacobians(
    v_world, R_nominal, delta, omega, u_sensor, t_body_sensor, R_body_sensor, v_meas, epsilon
):
    # type: (numpy.ndarray, Rot3, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, Rot3, float, float) -> T.Tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray]
    """
    Radar Doppler residual.

    Forward model:
        R(t) = R_nominal * exp(delta)
        v_body = R^T * v_world
        v_ant = v_body + omega x t_body_sensor
        u_body = R_body_sensor * u_sensor
        v_pred = u_body . v_ant
        residual = v_meas - v_pred
        res_D_v_world: (1x3) jacobian of res (1) wrt arg v_world (3)
        res_D_delta: (1x3) jacobian of res (1) wrt arg delta (3)
        res_D_omega: (1x3) jacobian of res (1) wrt arg omega (3)
        res_D_R_body_sensor: (1x3) jacobian of res (1) wrt arg R_body_sensor (3)
    """

    # Total ops: 584

    # Input arrays
    if v_world.shape == (3,):
        v_world = v_world.reshape((3, 1))
    elif v_world.shape != (3, 1):
        raise IndexError(
            "v_world is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                v_world.shape
            )
        )

    _R_nominal = R_nominal.data
    if delta.shape == (3,):
        delta = delta.reshape((3, 1))
    elif delta.shape != (3, 1):
        raise IndexError(
            "delta is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                delta.shape
            )
        )

    if omega.shape == (3,):
        omega = omega.reshape((3, 1))
    elif omega.shape != (3, 1):
        raise IndexError(
            "omega is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                omega.shape
            )
        )

    if u_sensor.shape == (3,):
        u_sensor = u_sensor.reshape((3, 1))
    elif u_sensor.shape != (3, 1):
        raise IndexError(
            "u_sensor is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                u_sensor.shape
            )
        )

    if t_body_sensor.shape == (3,):
        t_body_sensor = t_body_sensor.reshape((3, 1))
    elif t_body_sensor.shape != (3, 1):
        raise IndexError(
            "t_body_sensor is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                t_body_sensor.shape
            )
        )

    _R_body_sensor = R_body_sensor.data

    # Intermediate terms (183)
    _tmp0 = 2 * _R_body_sensor[2]
    _tmp1 = _R_body_sensor[1] * _tmp0
    _tmp2 = 2 * _R_body_sensor[0] * _R_body_sensor[3]
    _tmp3 = -_tmp2
    _tmp4 = _tmp1 + _tmp3
    _tmp5 = _R_body_sensor[2] ** 2
    _tmp6 = -2 * _tmp5
    _tmp7 = _R_body_sensor[0] ** 2
    _tmp8 = 1 - 2 * _tmp7
    _tmp9 = 2 * _R_body_sensor[1]
    _tmp10 = _R_body_sensor[0] * _tmp9
    _tmp11 = _R_body_sensor[3] * _tmp0
    _tmp12 = _tmp10 + _tmp11
    _tmp13 = _tmp12 * u_sensor[0, 0] + _tmp4 * u_sensor[2, 0] + u_sensor[1, 0] * (_tmp6 + _tmp8)
    _tmp14 = delta[2, 0] ** 2
    _tmp15 = delta[1, 0] ** 2
    _tmp16 = delta[0, 0] ** 2
    _tmp17 = _tmp14 + _tmp15 + _tmp16 + epsilon**2
    _tmp18 = math.sqrt(_tmp17)
    _tmp19 = (1.0 / 2.0) * _tmp18
    _tmp20 = math.sin(_tmp19)
    _tmp21 = _tmp20 / _tmp18
    _tmp22 = _R_nominal[3] * _tmp21
    _tmp23 = _tmp22 * delta[0, 0]
    _tmp24 = _R_nominal[1] * _tmp21
    _tmp25 = _tmp24 * delta[2, 0]
    _tmp26 = _R_nominal[2] * _tmp21
    _tmp27 = _tmp26 * delta[1, 0]
    _tmp28 = math.cos(_tmp19)
    _tmp29 = _R_nominal[0] * _tmp28
    _tmp30 = _tmp23 + _tmp25 - _tmp27 + _tmp29
    _tmp31 = _tmp22 * delta[1, 0]
    _tmp32 = _R_nominal[0] * _tmp21
    _tmp33 = _tmp32 * delta[2, 0]
    _tmp34 = _tmp26 * delta[0, 0]
    _tmp35 = _R_nominal[1] * _tmp28
    _tmp36 = _tmp31 - _tmp33 + _tmp34 + _tmp35
    _tmp37 = 2 * _tmp36
    _tmp38 = _tmp30 * _tmp37
    _tmp39 = _tmp32 * delta[0, 0]
    _tmp40 = _tmp24 * delta[1, 0]
    _tmp41 = _tmp26 * delta[2, 0]
    _tmp42 = _R_nominal[3] * _tmp28
    _tmp43 = -_tmp39 - _tmp40 - _tmp41 + _tmp42
    _tmp44 = _tmp22 * delta[2, 0]
    _tmp45 = _tmp32 * delta[1, 0]
    _tmp46 = _tmp24 * delta[0, 0]
    _tmp47 = _R_nominal[2] * _tmp28
    _tmp48 = _tmp44 + _tmp45 - _tmp46 + _tmp47
    _tmp49 = 2 * _tmp48
    _tmp50 = _tmp43 * _tmp49
    _tmp51 = _tmp38 - _tmp50
    _tmp52 = _tmp36 * _tmp49
    _tmp53 = 2 * _tmp30
    _tmp54 = _tmp43 * _tmp53
    _tmp55 = _tmp52 + _tmp54
    _tmp56 = -2 * _tmp30**2
    _tmp57 = 1 - 2 * _tmp48**2
    _tmp58 = _tmp56 + _tmp57
    _tmp59 = (
        _tmp51 * v_world[0, 0]
        + _tmp55 * v_world[2, 0]
        + _tmp58 * v_world[1, 0]
        - omega[0, 0] * t_body_sensor[2, 0]
        + omega[2, 0] * t_body_sensor[0, 0]
    )
    _tmp60 = _R_body_sensor[3] * _tmp9
    _tmp61 = _R_body_sensor[0] * _tmp0
    _tmp62 = _tmp60 + _tmp61
    _tmp63 = _R_body_sensor[1] ** 2
    _tmp64 = -2 * _tmp63
    _tmp65 = -_tmp11
    _tmp66 = _tmp10 + _tmp65
    _tmp67 = (
        _tmp62 * u_sensor[2, 0] + _tmp66 * u_sensor[1, 0] + u_sensor[0, 0] * (_tmp6 + _tmp64 + 1)
    )
    _tmp68 = -2 * _tmp36**2
    _tmp69 = _tmp57 + _tmp68
    _tmp70 = _tmp38 + _tmp50
    _tmp71 = _tmp30 * _tmp49
    _tmp72 = _tmp37 * _tmp43
    _tmp73 = _tmp71 - _tmp72
    _tmp74 = (
        _tmp69 * v_world[0, 0]
        + _tmp70 * v_world[1, 0]
        + _tmp73 * v_world[2, 0]
        + omega[1, 0] * t_body_sensor[2, 0]
        - omega[2, 0] * t_body_sensor[1, 0]
    )
    _tmp75 = _tmp56 + _tmp68 + 1
    _tmp76 = _tmp52 - _tmp54
    _tmp77 = _tmp71 + _tmp72
    _tmp78 = (
        _tmp75 * v_world[2, 0]
        + _tmp76 * v_world[1, 0]
        + _tmp77 * v_world[0, 0]
        + omega[0, 0] * t_body_sensor[1, 0]
        - omega[1, 0] * t_body_sensor[0, 0]
    )
    _tmp79 = -_tmp60
    _tmp80 = _tmp61 + _tmp79
    _tmp81 = _tmp1 + _tmp2
    _tmp82 = _tmp80 * u_sensor[0, 0] + _tmp81 * u_sensor[1, 0] + u_sensor[2, 0] * (_tmp64 + _tmp8)
    _tmp83 = _tmp20 / _tmp17 ** (3.0 / 2.0)
    _tmp84 = _R_nominal[2] * _tmp83
    _tmp85 = delta[0, 0] * delta[2, 0]
    _tmp86 = _tmp84 * _tmp85
    _tmp87 = -_tmp32
    _tmp88 = (1.0 / 2.0) / _tmp17
    _tmp89 = _tmp29 * _tmp88
    _tmp90 = _R_nominal[0] * _tmp83
    _tmp91 = _tmp47 * _tmp88
    _tmp92 = _tmp85 * _tmp91
    _tmp93 = _R_nominal[1] * _tmp83
    _tmp94 = delta[0, 0] * delta[1, 0]
    _tmp95 = _tmp35 * _tmp88
    _tmp96 = _tmp93 * _tmp94 - _tmp94 * _tmp95
    _tmp97 = (
        -_tmp16 * _tmp89 + _tmp16 * _tmp90 - 1.0 / 2.0 * _tmp23 + _tmp86 + _tmp87 - _tmp92 + _tmp96
    )
    _tmp98 = _tmp49 * _tmp97
    _tmp99 = _tmp90 * _tmp94
    _tmp100 = -_tmp24
    _tmp101 = _tmp89 * _tmp94
    _tmp102 = _R_nominal[3] * _tmp83
    _tmp103 = _tmp102 * delta[2, 0]
    _tmp104 = _tmp42 * _tmp88
    _tmp105 = -_tmp103 * delta[0, 0] + _tmp104 * _tmp85
    _tmp106 = (
        _tmp100
        + _tmp101
        + _tmp105
        + _tmp16 * _tmp93
        - _tmp16 * _tmp95
        - 1.0 / 2.0 * _tmp34
        - _tmp99
    )
    _tmp107 = 2 * _tmp43
    _tmp108 = _tmp106 * _tmp107
    _tmp109 = -_tmp102 * _tmp94 + _tmp104 * _tmp94
    _tmp110 = -_tmp85 * _tmp89 + _tmp85 * _tmp90
    _tmp111 = _tmp109 + _tmp110 - _tmp16 * _tmp84 + _tmp16 * _tmp91 + _tmp26 - 1.0 / 2.0 * _tmp46
    _tmp112 = _tmp85 * _tmp93
    _tmp113 = _tmp84 * _tmp94
    _tmp114 = _tmp91 * _tmp94
    _tmp115 = _tmp85 * _tmp95
    _tmp116 = (
        -_tmp102 * _tmp16
        + _tmp104 * _tmp16
        - _tmp112
        + _tmp113
        - _tmp114
        + _tmp115
        + _tmp22
        - 1.0 / 2.0 * _tmp39
    )
    _tmp117 = _tmp111 * _tmp53 + _tmp116 * _tmp37
    _tmp118 = _tmp53 * _tmp97
    _tmp119 = _tmp107 * _tmp116
    _tmp120 = _tmp106 * _tmp37 + _tmp111 * _tmp49
    _tmp121 = 4 * _tmp48
    _tmp122 = -_tmp106 * _tmp121
    _tmp123 = 4 * _tmp30
    _tmp124 = -_tmp116 * _tmp123
    _tmp125 = 4 * _tmp36
    _tmp126 = -_tmp111 * _tmp125
    _tmp127 = _tmp37 * _tmp97
    _tmp128 = _tmp107 * _tmp111
    _tmp129 = _tmp106 * _tmp53 + _tmp116 * _tmp49
    _tmp130 = delta[1, 0] * delta[2, 0]
    _tmp131 = _tmp130 * _tmp84 - _tmp130 * _tmp91
    _tmp132 = (
        _tmp100
        - _tmp101
        + _tmp131
        + _tmp15 * _tmp93
        - _tmp15 * _tmp95
        - 1.0 / 2.0 * _tmp31
        + _tmp99
    )
    _tmp133 = _tmp132 * _tmp37
    _tmp134 = _tmp130 * _tmp90
    _tmp135 = _tmp130 * _tmp89
    _tmp136 = (
        -_tmp102 * _tmp15
        + _tmp104 * _tmp15
        - _tmp113
        + _tmp114
        + _tmp134
        - _tmp135
        + _tmp22
        - 1.0 / 2.0 * _tmp40
    )
    _tmp137 = _tmp107 * _tmp136
    _tmp138 = -_tmp103 * delta[1, 0] + _tmp104 * _tmp130
    _tmp139 = _tmp138 + _tmp15 * _tmp89 - _tmp15 * _tmp90 - 1.0 / 2.0 * _tmp27 + _tmp32 + _tmp96
    _tmp140 = _tmp130 * _tmp93
    _tmp141 = -_tmp26
    _tmp142 = _tmp130 * _tmp95
    _tmp143 = (
        _tmp109
        - _tmp140
        + _tmp141
        + _tmp142
        + _tmp15 * _tmp84
        - _tmp15 * _tmp91
        - 1.0 / 2.0 * _tmp45
    )
    _tmp144 = _tmp139 * _tmp53 + _tmp143 * _tmp49
    _tmp145 = -_tmp125 * _tmp136
    _tmp146 = -_tmp123 * _tmp143
    _tmp147 = _tmp132 * _tmp53
    _tmp148 = _tmp107 * _tmp143
    _tmp149 = _tmp136 * _tmp49 + _tmp139 * _tmp37
    _tmp150 = -_tmp121 * _tmp139
    _tmp151 = _tmp132 * _tmp49
    _tmp152 = _tmp107 * _tmp139
    _tmp153 = _tmp136 * _tmp53 + _tmp143 * _tmp37
    _tmp154 = _tmp14 * _tmp88
    _tmp155 = (
        -_tmp102 * _tmp14
        + _tmp112
        - _tmp115
        - _tmp134
        + _tmp135
        + _tmp154 * _tmp42
        + _tmp22
        - 1.0 / 2.0 * _tmp41
    )
    _tmp156 = _tmp107 * _tmp155
    _tmp157 = (
        _tmp110
        + _tmp14 * _tmp84
        + _tmp140
        + _tmp141
        - _tmp142
        - _tmp154 * _tmp47
        - 1.0 / 2.0 * _tmp44
    )
    _tmp158 = _tmp157 * _tmp49
    _tmp159 = (
        _tmp138 + _tmp14 * _tmp90 - _tmp154 * _tmp29 - 1.0 / 2.0 * _tmp25 - _tmp86 + _tmp87 + _tmp92
    )
    _tmp160 = _tmp105 + _tmp131 - _tmp14 * _tmp93 + _tmp154 * _tmp35 + _tmp24 - 1.0 / 2.0 * _tmp33
    _tmp161 = _tmp159 * _tmp53 + _tmp160 * _tmp37
    _tmp162 = -_tmp125 * _tmp159
    _tmp163 = -_tmp121 * _tmp155
    _tmp164 = _tmp107 * _tmp159
    _tmp165 = _tmp157 * _tmp37
    _tmp166 = _tmp155 * _tmp53 + _tmp160 * _tmp49
    _tmp167 = _tmp107 * _tmp160
    _tmp168 = _tmp157 * _tmp53
    _tmp169 = _tmp155 * _tmp37 + _tmp159 * _tmp49
    _tmp170 = -_tmp123 * _tmp160
    _tmp171 = _R_body_sensor[3] ** 2
    _tmp172 = -_tmp171
    _tmp173 = -_tmp63
    _tmp174 = -_tmp1
    _tmp175 = _tmp171 + _tmp173
    _tmp176 = -_tmp7
    _tmp177 = _tmp176 + _tmp5
    _tmp178 = -_tmp10
    _tmp179 = -_tmp61
    _tmp180 = -_tmp5
    _tmp181 = _tmp180 + _tmp7
    _tmp182 = _tmp172 + _tmp63

    # Output terms
    _res = numpy.zeros(1)
    _res[0] = -_tmp13 * _tmp59 - _tmp67 * _tmp74 - _tmp78 * _tmp82 + v_meas
    _res_D_v_world = numpy.zeros(3)
    _res_D_v_world[0] = -_tmp13 * _tmp51 - _tmp67 * _tmp69 - _tmp77 * _tmp82
    _res_D_v_world[1] = -_tmp13 * _tmp58 - _tmp67 * _tmp70 - _tmp76 * _tmp82
    _res_D_v_world[2] = -_tmp13 * _tmp55 - _tmp67 * _tmp73 - _tmp75 * _tmp82
    _res_D_delta = numpy.zeros(3)
    _res_D_delta[0] = (
        -_tmp13
        * (
            v_world[0, 0] * (-_tmp108 + _tmp117 - _tmp98)
            + v_world[1, 0] * (_tmp122 + _tmp124)
            + v_world[2, 0] * (_tmp118 + _tmp119 + _tmp120)
        )
        - _tmp67
        * (
            v_world[0, 0] * (_tmp122 + _tmp126)
            + v_world[1, 0] * (_tmp108 + _tmp117 + _tmp98)
            + v_world[2, 0] * (-_tmp127 - _tmp128 + _tmp129)
        )
        - _tmp82
        * (
            v_world[0, 0] * (_tmp127 + _tmp128 + _tmp129)
            + v_world[1, 0] * (-_tmp118 - _tmp119 + _tmp120)
            + v_world[2, 0] * (_tmp124 + _tmp126)
        )
    )
    _res_D_delta[1] = (
        -_tmp13
        * (
            v_world[0, 0] * (-_tmp151 - _tmp152 + _tmp153)
            + v_world[1, 0] * (_tmp146 + _tmp150)
            + v_world[2, 0] * (_tmp147 + _tmp148 + _tmp149)
        )
        - _tmp67
        * (
            v_world[0, 0] * (_tmp145 + _tmp150)
            + v_world[1, 0] * (_tmp151 + _tmp152 + _tmp153)
            + v_world[2, 0] * (-_tmp133 - _tmp137 + _tmp144)
        )
        - _tmp82
        * (
            v_world[0, 0] * (_tmp133 + _tmp137 + _tmp144)
            + v_world[1, 0] * (-_tmp147 - _tmp148 + _tmp149)
            + v_world[2, 0] * (_tmp145 + _tmp146)
        )
    )
    _res_D_delta[2] = (
        -_tmp13
        * (
            v_world[0, 0] * (-_tmp156 - _tmp158 + _tmp161)
            + v_world[1, 0] * (_tmp163 + _tmp170)
            + v_world[2, 0] * (_tmp167 + _tmp168 + _tmp169)
        )
        - _tmp67
        * (
            v_world[0, 0] * (_tmp162 + _tmp163)
            + v_world[1, 0] * (_tmp156 + _tmp158 + _tmp161)
            + v_world[2, 0] * (-_tmp164 - _tmp165 + _tmp166)
        )
        - _tmp82
        * (
            v_world[0, 0] * (_tmp164 + _tmp165 + _tmp166)
            + v_world[1, 0] * (-_tmp167 - _tmp168 + _tmp169)
            + v_world[2, 0] * (_tmp162 + _tmp170)
        )
    )
    _res_D_omega = numpy.zeros(3)
    _res_D_omega[0] = _tmp13 * t_body_sensor[2, 0] - _tmp82 * t_body_sensor[1, 0]
    _res_D_omega[1] = -_tmp67 * t_body_sensor[2, 0] + _tmp82 * t_body_sensor[0, 0]
    _res_D_omega[2] = -_tmp13 * t_body_sensor[0, 0] + _tmp67 * t_body_sensor[1, 0]
    _res_D_R_body_sensor = numpy.zeros(3)
    _res_D_R_body_sensor[0] = (
        -_tmp59 * (_tmp4 * u_sensor[1, 0] + u_sensor[2, 0] * (_tmp172 + _tmp173 + _tmp5 + _tmp7))
        - _tmp74 * (_tmp62 * u_sensor[1, 0] + u_sensor[2, 0] * (_tmp11 + _tmp178))
        - _tmp78 * (u_sensor[1, 0] * (_tmp175 + _tmp177) + u_sensor[2, 0] * (_tmp174 + _tmp3))
    )
    _res_D_R_body_sensor[1] = (
        -_tmp59 * (_tmp12 * u_sensor[2, 0] + u_sensor[0, 0] * (_tmp174 + _tmp2))
        - _tmp74 * (u_sensor[0, 0] * (_tmp179 + _tmp79) + u_sensor[2, 0] * (_tmp175 + _tmp181))
        - _tmp78 * (_tmp80 * u_sensor[2, 0] + u_sensor[0, 0] * (_tmp181 + _tmp182))
    )
    _res_D_R_body_sensor[2] = (
        -_tmp59
        * (
            u_sensor[0, 0] * (_tmp171 + _tmp176 + _tmp180 + _tmp63)
            + u_sensor[1, 0] * (_tmp178 + _tmp65)
        )
        - _tmp74 * (_tmp66 * u_sensor[0, 0] + u_sensor[1, 0] * (_tmp177 + _tmp182))
        - _tmp78 * (_tmp81 * u_sensor[0, 0] + u_sensor[1, 0] * (_tmp179 + _tmp60))
    )
    return _res, _res_D_v_world, _res_D_delta, _res_D_omega, _res_D_R_body_sensor


# ======================================================================
# ACCELEROMETER RESIDUAL + JACOBIANS
# ======================================================================


# --- From: accel_residual_with_jacobians025.py ---

def accel_residual_with_jacobians(a_world, R_nominal, delta, g_world, z_acc, b_a, epsilon):
    # type: (numpy.ndarray, Rot3, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, float) -> T.Tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray]
    """
    Accelerometer residual.

    Forward model:
        R(t) = R_nominal * exp(delta)
        predicted_specific_force = R^T * (a_world - g_world)
        residual = z_acc - predicted_specific_force - b_a
        res_D_a_world: (3x3) jacobian of res (3) wrt arg a_world (3)
        res_D_delta: (3x3) jacobian of res (3) wrt arg delta (3)
        res_D_b_a: (3x3) jacobian of res (3) wrt arg b_a (3)
    """

    # Total ops: 443

    # Input arrays
    if a_world.shape == (3,):
        a_world = a_world.reshape((3, 1))
    elif a_world.shape != (3, 1):
        raise IndexError(
            "a_world is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                a_world.shape
            )
        )

    _R_nominal = R_nominal.data
    if delta.shape == (3,):
        delta = delta.reshape((3, 1))
    elif delta.shape != (3, 1):
        raise IndexError(
            "delta is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                delta.shape
            )
        )

    if g_world.shape == (3,):
        g_world = g_world.reshape((3, 1))
    elif g_world.shape != (3, 1):
        raise IndexError(
            "g_world is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                g_world.shape
            )
        )

    if z_acc.shape == (3,):
        z_acc = z_acc.reshape((3, 1))
    elif z_acc.shape != (3, 1):
        raise IndexError(
            "z_acc is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                z_acc.shape
            )
        )

    if b_a.shape == (3,):
        b_a = b_a.reshape((3, 1))
    elif b_a.shape != (3, 1):
        raise IndexError(
            "b_a is expected to have shape (3, 1) or (3,); instead had shape {}".format(b_a.shape)
        )

    # Intermediate terms (148)
    _tmp0 = a_world[1, 0] - g_world[1, 0]
    _tmp1 = delta[2, 0] ** 2
    _tmp2 = delta[1, 0] ** 2
    _tmp3 = delta[0, 0] ** 2
    _tmp4 = _tmp1 + _tmp2 + _tmp3 + epsilon**2
    _tmp5 = math.sqrt(_tmp4)
    _tmp6 = (1.0 / 2.0) * _tmp5
    _tmp7 = math.sin(_tmp6)
    _tmp8 = _tmp7 / _tmp5
    _tmp9 = _R_nominal[3] * _tmp8
    _tmp10 = _tmp9 * delta[1, 0]
    _tmp11 = _R_nominal[0] * _tmp8
    _tmp12 = _tmp11 * delta[2, 0]
    _tmp13 = _R_nominal[2] * _tmp8
    _tmp14 = _tmp13 * delta[0, 0]
    _tmp15 = math.cos(_tmp6)
    _tmp16 = _R_nominal[1] * _tmp15
    _tmp17 = _tmp10 - _tmp12 + _tmp14 + _tmp16
    _tmp18 = _tmp9 * delta[0, 0]
    _tmp19 = _R_nominal[1] * _tmp8
    _tmp20 = _tmp19 * delta[2, 0]
    _tmp21 = _tmp13 * delta[1, 0]
    _tmp22 = _R_nominal[0] * _tmp15
    _tmp23 = _tmp18 + _tmp20 - _tmp21 + _tmp22
    _tmp24 = 2 * _tmp23
    _tmp25 = _tmp17 * _tmp24
    _tmp26 = _tmp9 * delta[2, 0]
    _tmp27 = _tmp11 * delta[1, 0]
    _tmp28 = _tmp19 * delta[0, 0]
    _tmp29 = _R_nominal[2] * _tmp15
    _tmp30 = _tmp26 + _tmp27 - _tmp28 + _tmp29
    _tmp31 = _tmp11 * delta[0, 0]
    _tmp32 = _tmp19 * delta[1, 0]
    _tmp33 = _tmp13 * delta[2, 0]
    _tmp34 = _R_nominal[3] * _tmp15
    _tmp35 = -2 * _tmp31 - 2 * _tmp32 - 2 * _tmp33 + 2 * _tmp34
    _tmp36 = _tmp30 * _tmp35
    _tmp37 = 2 * _tmp17**2
    _tmp38 = -_tmp37
    _tmp39 = 2 * _tmp30**2
    _tmp40 = 1 - _tmp39
    _tmp41 = a_world[0, 0] - g_world[0, 0]
    _tmp42 = a_world[2, 0] - g_world[2, 0]
    _tmp43 = 2 * _tmp30
    _tmp44 = _tmp23 * _tmp43
    _tmp45 = _tmp17 * _tmp35
    _tmp46 = -_tmp45
    _tmp47 = -_tmp36
    _tmp48 = 2 * _tmp23**2
    _tmp49 = -_tmp48
    _tmp50 = _tmp17 * _tmp43
    _tmp51 = _tmp23 * _tmp35
    _tmp52 = -_tmp51
    _tmp53 = _tmp39 - 1
    _tmp54 = -_tmp25
    _tmp55 = -_tmp44
    _tmp56 = -_tmp50
    _tmp57 = _tmp7 / _tmp4 ** (3.0 / 2.0)
    _tmp58 = _R_nominal[2] * _tmp57
    _tmp59 = _tmp58 * delta[2, 0]
    _tmp60 = _tmp59 * delta[0, 0]
    _tmp61 = -_tmp11
    _tmp62 = (1.0 / 2.0) / _tmp4
    _tmp63 = _tmp22 * _tmp62
    _tmp64 = _tmp3 * _tmp57
    _tmp65 = _tmp29 * _tmp62
    _tmp66 = delta[0, 0] * delta[2, 0]
    _tmp67 = _tmp65 * _tmp66
    _tmp68 = _R_nominal[1] * _tmp57
    _tmp69 = _tmp68 * delta[0, 0]
    _tmp70 = delta[0, 0] * delta[1, 0]
    _tmp71 = _tmp16 * _tmp62
    _tmp72 = _tmp69 * delta[1, 0] - _tmp70 * _tmp71
    _tmp73 = (
        _R_nominal[0] * _tmp64
        - 1.0 / 2.0 * _tmp18
        - _tmp3 * _tmp63
        + _tmp60
        + _tmp61
        - _tmp67
        + _tmp72
    )
    _tmp74 = 2 * _tmp17
    _tmp75 = _tmp73 * _tmp74
    _tmp76 = _R_nominal[0] * _tmp57
    _tmp77 = _tmp76 * delta[2, 0]
    _tmp78 = -_tmp63 * _tmp66 + _tmp77 * delta[0, 0]
    _tmp79 = _R_nominal[3] * _tmp57
    _tmp80 = _tmp34 * _tmp62
    _tmp81 = -_tmp70 * _tmp79 + _tmp70 * _tmp80
    _tmp82 = (
        -_R_nominal[2] * _tmp64 + _tmp13 - 1.0 / 2.0 * _tmp28 + _tmp3 * _tmp65 + _tmp78 + _tmp81
    )
    _tmp83 = _tmp35 * _tmp82
    _tmp84 = -_tmp19
    _tmp85 = _tmp70 * _tmp76
    _tmp86 = _tmp63 * _tmp70
    _tmp87 = -_tmp66 * _tmp79 + _tmp66 * _tmp80
    _tmp88 = (
        _R_nominal[1] * _tmp64
        - 1.0 / 2.0 * _tmp14
        - _tmp3 * _tmp71
        + _tmp84
        - _tmp85
        + _tmp86
        + _tmp87
    )
    _tmp89 = _tmp69 * delta[2, 0]
    _tmp90 = _tmp58 * _tmp70
    _tmp91 = _tmp65 * _tmp70
    _tmp92 = _tmp66 * _tmp71
    _tmp93 = (
        -_R_nominal[3] * _tmp64
        + _tmp3 * _tmp80
        - 1.0 / 2.0 * _tmp31
        - _tmp89
        + _tmp9
        + _tmp90
        - _tmp91
        + _tmp92
    )
    _tmp94 = _tmp24 * _tmp88 + _tmp43 * _tmp93
    _tmp95 = 4 * _tmp17
    _tmp96 = -_tmp82 * _tmp95
    _tmp97 = 4 * _tmp30
    _tmp98 = -_tmp88 * _tmp97
    _tmp99 = _tmp43 * _tmp73
    _tmp100 = _tmp35 * _tmp88
    _tmp101 = _tmp24 * _tmp82 + _tmp74 * _tmp93
    _tmp102 = 4 * _tmp23
    _tmp103 = -_tmp102 * _tmp93
    _tmp104 = _tmp24 * _tmp73
    _tmp105 = _tmp35 * _tmp93
    _tmp106 = _tmp43 * _tmp82 + _tmp74 * _tmp88
    _tmp107 = _tmp77 * delta[1, 0]
    _tmp108 = _tmp2 * _tmp62
    _tmp109 = delta[1, 0] * delta[2, 0]
    _tmp110 = _tmp109 * _tmp63
    _tmp111 = (
        _tmp107
        + _tmp108 * _tmp34
        - _tmp110
        - _tmp2 * _tmp79
        - 1.0 / 2.0 * _tmp32
        + _tmp9
        - _tmp90
        + _tmp91
    )
    _tmp112 = -_tmp111 * _tmp95
    _tmp113 = -_tmp109 * _tmp79 + _tmp109 * _tmp80
    _tmp114 = _tmp11 + _tmp113 + _tmp2 * _tmp63 - _tmp2 * _tmp76 - 1.0 / 2.0 * _tmp21 + _tmp72
    _tmp115 = -_tmp114 * _tmp97
    _tmp116 = -_tmp109 * _tmp65 + _tmp59 * delta[1, 0]
    _tmp117 = (
        -1.0 / 2.0 * _tmp10 - _tmp108 * _tmp16 + _tmp116 + _tmp2 * _tmp68 + _tmp84 + _tmp85 - _tmp86
    )
    _tmp118 = _tmp117 * _tmp43
    _tmp119 = _tmp114 * _tmp35
    _tmp120 = -_tmp13
    _tmp121 = _tmp109 * _tmp68
    _tmp122 = _tmp109 * _tmp71
    _tmp123 = (
        -_tmp108 * _tmp29
        + _tmp120
        - _tmp121
        + _tmp122
        + _tmp2 * _tmp58
        - 1.0 / 2.0 * _tmp27
        + _tmp81
    )
    _tmp124 = _tmp111 * _tmp24 + _tmp123 * _tmp74
    _tmp125 = _tmp117 * _tmp74
    _tmp126 = _tmp111 * _tmp35
    _tmp127 = _tmp114 * _tmp24 + _tmp123 * _tmp43
    _tmp128 = -_tmp102 * _tmp123
    _tmp129 = _tmp117 * _tmp24
    _tmp130 = _tmp123 * _tmp35
    _tmp131 = _tmp111 * _tmp43 + _tmp114 * _tmp74
    _tmp132 = (
        -_tmp1 * _tmp79
        + _tmp1 * _tmp80
        - _tmp107
        + _tmp110
        - 1.0 / 2.0 * _tmp33
        + _tmp89
        + _tmp9
        - _tmp92
    )
    _tmp133 = _tmp132 * _tmp35
    _tmp134 = (
        _tmp1 * _tmp58 - _tmp1 * _tmp65 + _tmp120 + _tmp121 - _tmp122 - 1.0 / 2.0 * _tmp26 + _tmp78
    )
    _tmp135 = _tmp134 * _tmp43
    _tmp136 = (
        -_tmp1 * _tmp63 + _tmp1 * _tmp76 + _tmp113 - 1.0 / 2.0 * _tmp20 - _tmp60 + _tmp61 + _tmp67
    )
    _tmp137 = -_tmp1 * _tmp68 + _tmp1 * _tmp71 + _tmp116 - 1.0 / 2.0 * _tmp12 + _tmp19 + _tmp87
    _tmp138 = _tmp136 * _tmp24 + _tmp137 * _tmp74
    _tmp139 = -_tmp136 * _tmp95
    _tmp140 = -_tmp132 * _tmp97
    _tmp141 = _tmp136 * _tmp35
    _tmp142 = _tmp134 * _tmp74
    _tmp143 = _tmp132 * _tmp24 + _tmp137 * _tmp43
    _tmp144 = _tmp137 * _tmp35
    _tmp145 = _tmp134 * _tmp24
    _tmp146 = _tmp132 * _tmp74 + _tmp136 * _tmp43
    _tmp147 = -_tmp102 * _tmp137

    # Output terms
    _res = numpy.zeros(3)
    _res[0] = (
        -_tmp0 * (_tmp25 + _tmp36)
        - _tmp41 * (_tmp38 + _tmp40)
        - _tmp42 * (_tmp44 + _tmp46)
        - b_a[0, 0]
        + z_acc[0, 0]
    )
    _res[1] = (
        -_tmp0 * (_tmp40 + _tmp49)
        - _tmp41 * (_tmp25 + _tmp47)
        - _tmp42 * (_tmp50 + _tmp51)
        - b_a[1, 0]
        + z_acc[1, 0]
    )
    _res[2] = (
        -_tmp0 * (_tmp50 + _tmp52)
        - _tmp41 * (_tmp44 + _tmp45)
        - _tmp42 * (_tmp38 + _tmp49 + 1)
        - b_a[2, 0]
        + z_acc[2, 0]
    )
    _res_D_a_world = numpy.zeros((3, 3))
    _res_D_a_world[0, 0] = _tmp37 + _tmp53
    _res_D_a_world[1, 0] = _tmp36 + _tmp54
    _res_D_a_world[2, 0] = _tmp46 + _tmp55
    _res_D_a_world[0, 1] = _tmp47 + _tmp54
    _res_D_a_world[1, 1] = _tmp48 + _tmp53
    _res_D_a_world[2, 1] = _tmp51 + _tmp56
    _res_D_a_world[0, 2] = _tmp45 + _tmp55
    _res_D_a_world[1, 2] = _tmp52 + _tmp56
    _res_D_a_world[2, 2] = _tmp37 + _tmp48 - 1
    _res_D_delta = numpy.zeros((3, 3))
    _res_D_delta[0, 0] = (
        -_tmp0 * (_tmp100 + _tmp101 + _tmp99)
        - _tmp41 * (_tmp96 + _tmp98)
        - _tmp42 * (-_tmp75 - _tmp83 + _tmp94)
    )
    _res_D_delta[1, 0] = (
        -_tmp0 * (_tmp103 + _tmp98)
        - _tmp41 * (-_tmp100 + _tmp101 - _tmp99)
        - _tmp42 * (_tmp104 + _tmp105 + _tmp106)
    )
    _res_D_delta[2, 0] = (
        -_tmp0 * (-_tmp104 - _tmp105 + _tmp106)
        - _tmp41 * (_tmp75 + _tmp83 + _tmp94)
        - _tmp42 * (_tmp103 + _tmp96)
    )
    _res_D_delta[0, 1] = (
        -_tmp0 * (_tmp118 + _tmp119 + _tmp124)
        - _tmp41 * (_tmp112 + _tmp115)
        - _tmp42 * (-_tmp125 - _tmp126 + _tmp127)
    )
    _res_D_delta[1, 1] = (
        -_tmp0 * (_tmp115 + _tmp128)
        - _tmp41 * (-_tmp118 - _tmp119 + _tmp124)
        - _tmp42 * (_tmp129 + _tmp130 + _tmp131)
    )
    _res_D_delta[2, 1] = (
        -_tmp0 * (-_tmp129 - _tmp130 + _tmp131)
        - _tmp41 * (_tmp125 + _tmp126 + _tmp127)
        - _tmp42 * (_tmp112 + _tmp128)
    )
    _res_D_delta[0, 2] = (
        -_tmp0 * (_tmp133 + _tmp135 + _tmp138)
        - _tmp41 * (_tmp139 + _tmp140)
        - _tmp42 * (-_tmp141 - _tmp142 + _tmp143)
    )
    _res_D_delta[1, 2] = (
        -_tmp0 * (_tmp140 + _tmp147)
        - _tmp41 * (-_tmp133 - _tmp135 + _tmp138)
        - _tmp42 * (_tmp144 + _tmp145 + _tmp146)
    )
    _res_D_delta[2, 2] = (
        -_tmp0 * (-_tmp144 - _tmp145 + _tmp146)
        - _tmp41 * (_tmp141 + _tmp142 + _tmp143)
        - _tmp42 * (_tmp139 + _tmp147)
    )
    _res_D_b_a = numpy.zeros((3, 3))
    _res_D_b_a[0, 0] = -1
    _res_D_b_a[1, 0] = 0
    _res_D_b_a[2, 0] = 0
    _res_D_b_a[0, 1] = 0
    _res_D_b_a[1, 1] = -1
    _res_D_b_a[2, 1] = 0
    _res_D_b_a[0, 2] = 0
    _res_D_b_a[1, 2] = 0
    _res_D_b_a[2, 2] = -1
    return _res, _res_D_a_world, _res_D_delta, _res_D_b_a


# ======================================================================
# GYROSCOPE RESIDUAL + JACOBIANS
# ======================================================================


# --- From: gyro_residual_with_jacobians124.py ---

def gyro_residual_with_jacobians(omega_nominal, delta, delta_dot, z_gyro, b_g, epsilon):
    # type: (numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, float) -> T.Tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray]
    """
    Gyroscope residual with proper SO(3) right Jacobian.

    Full angular velocity model:
        R(t) = R_nominal * exp(delta)
        omega_body = exp(-[delta]_x) * omega_nominal + J_r(delta) * delta_dot

    where J_r(delta) is the right Jacobian of SO(3):
        J_r(phi) = I - (1-cos||phi||)/||phi||^2 [phi]_x
                     + (||phi||-sin||phi||)/||phi||^3 [phi]_x^2

    For small delta: omega ≈ omega_nominal + delta_dot (recovers linear model).

    Residual: r = z_gyro - omega_body - b_g
        res_D_delta: (3x3) jacobian of res (3) wrt arg delta (3)
        res_D_delta_dot: (3x3) jacobian of res (3) wrt arg delta_dot (3)
        res_D_b_g: (3x3) jacobian of res (3) wrt arg b_g (3)
    """

    # Total ops: 517

    # Input arrays
    if omega_nominal.shape == (3,):
        omega_nominal = omega_nominal.reshape((3, 1))
    elif omega_nominal.shape != (3, 1):
        raise IndexError(
            "omega_nominal is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                omega_nominal.shape
            )
        )

    if delta.shape == (3,):
        delta = delta.reshape((3, 1))
    elif delta.shape != (3, 1):
        raise IndexError(
            "delta is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                delta.shape
            )
        )

    if delta_dot.shape == (3,):
        delta_dot = delta_dot.reshape((3, 1))
    elif delta_dot.shape != (3, 1):
        raise IndexError(
            "delta_dot is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                delta_dot.shape
            )
        )

    if z_gyro.shape == (3,):
        z_gyro = z_gyro.reshape((3, 1))
    elif z_gyro.shape != (3, 1):
        raise IndexError(
            "z_gyro is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                z_gyro.shape
            )
        )

    if b_g.shape == (3,):
        b_g = b_g.reshape((3, 1))
    elif b_g.shape != (3, 1):
        raise IndexError(
            "b_g is expected to have shape (3, 1) or (3,); instead had shape {}".format(b_g.shape)
        )

    # Intermediate terms (191)
    _tmp0 = delta[2, 0] ** 2
    _tmp1 = delta[1, 0] ** 2
    _tmp2 = delta[0, 0] ** 2
    _tmp3 = _tmp0 + _tmp1 + _tmp2 + epsilon**2
    _tmp4 = math.sqrt(_tmp3)
    _tmp5 = math.sin(_tmp4)
    _tmp6 = _tmp4 - _tmp5
    _tmp7 = _tmp3 ** (-3.0 / 2.0)
    _tmp8 = _tmp6 * _tmp7
    _tmp9 = _tmp8 * delta[0, 0]
    _tmp10 = _tmp9 * delta[1, 0]
    _tmp11 = 1 / _tmp3
    _tmp12 = math.cos(_tmp4)
    _tmp13 = 1 - _tmp12
    _tmp14 = _tmp11 * _tmp13
    _tmp15 = _tmp14 * delta[2, 0]
    _tmp16 = _tmp9 * delta[2, 0]
    _tmp17 = _tmp14 * delta[1, 0]
    _tmp18 = -_tmp17
    _tmp19 = (1.0 / 2.0) * _tmp4
    _tmp20 = math.sin(_tmp19)
    _tmp21 = _tmp20**2
    _tmp22 = _tmp1 * _tmp11
    _tmp23 = _tmp21 * _tmp22
    _tmp24 = -2 * _tmp23
    _tmp25 = _tmp11 * _tmp21
    _tmp26 = _tmp0 * _tmp25
    _tmp27 = -2 * _tmp26
    _tmp28 = _tmp1 * _tmp8
    _tmp29 = -_tmp28
    _tmp30 = _tmp0 * _tmp8
    _tmp31 = 1 - _tmp30
    _tmp32 = delta[0, 0] * delta[2, 0]
    _tmp33 = _tmp25 * _tmp32
    _tmp34 = 2 * _tmp33
    _tmp35 = 1 / _tmp4
    _tmp36 = _tmp35 * delta[1, 0]
    _tmp37 = math.cos(_tmp19)
    _tmp38 = 2 * _tmp20 * _tmp37
    _tmp39 = _tmp36 * _tmp38
    _tmp40 = delta[0, 0] * delta[1, 0]
    _tmp41 = _tmp25 * _tmp40
    _tmp42 = 2 * _tmp41
    _tmp43 = _tmp35 * delta[2, 0]
    _tmp44 = _tmp38 * _tmp43
    _tmp45 = -_tmp15
    _tmp46 = _tmp8 * delta[1, 0]
    _tmp47 = _tmp46 * delta[2, 0]
    _tmp48 = _tmp14 * delta[0, 0]
    _tmp49 = _tmp2 * _tmp25
    _tmp50 = 1 - 2 * _tmp49
    _tmp51 = _tmp2 * _tmp8
    _tmp52 = -_tmp51
    _tmp53 = delta[1, 0] * delta[2, 0]
    _tmp54 = _tmp25 * _tmp53
    _tmp55 = 2 * _tmp54
    _tmp56 = _tmp35 * delta[0, 0]
    _tmp57 = _tmp38 * _tmp56
    _tmp58 = -_tmp48
    _tmp59 = _tmp25 * delta[2, 0]
    _tmp60 = 2 * _tmp59
    _tmp61 = _tmp3 ** (-2)
    _tmp62 = _tmp2 * _tmp61
    _tmp63 = 4 * _tmp21
    _tmp64 = _tmp62 * _tmp63
    _tmp65 = _tmp64 * delta[2, 0]
    _tmp66 = _tmp2 * _tmp7
    _tmp67 = _tmp38 * _tmp66
    _tmp68 = _tmp67 * delta[2, 0]
    _tmp69 = _tmp60 - _tmp65 + _tmp68
    _tmp70 = _tmp37**2
    _tmp71 = _tmp11 * _tmp70
    _tmp72 = _tmp40 * _tmp71
    _tmp73 = _tmp38 * _tmp7
    _tmp74 = _tmp40 * _tmp73
    _tmp75 = _tmp41 - _tmp72 + _tmp74
    _tmp76 = _tmp25 * delta[1, 0]
    _tmp77 = 2 * _tmp76
    _tmp78 = _tmp64 * delta[1, 0]
    _tmp79 = _tmp67 * delta[1, 0]
    _tmp80 = _tmp77 - _tmp78 + _tmp79
    _tmp81 = _tmp32 * _tmp71
    _tmp82 = _tmp32 * _tmp73
    _tmp83 = -_tmp33 + _tmp81 - _tmp82
    _tmp84 = 3 * _tmp6 / _tmp3 ** (5.0 / 2.0)
    _tmp85 = _tmp84 * delta[1, 0]
    _tmp86 = _tmp2 * _tmp85
    _tmp87 = -_tmp12 * _tmp56 + _tmp56
    _tmp88 = _tmp7 * _tmp87
    _tmp89 = _tmp40 * _tmp88 + _tmp46 - _tmp86
    _tmp90 = 2 * _tmp13
    _tmp91 = _tmp61 * _tmp90
    _tmp92 = _tmp32 * _tmp91
    _tmp93 = _tmp5 * _tmp7
    _tmp94 = _tmp32 * _tmp93
    _tmp95 = -_tmp92 + _tmp94
    _tmp96 = _tmp84 * delta[2, 0]
    _tmp97 = _tmp2 * _tmp96
    _tmp98 = _tmp8 * delta[2, 0]
    _tmp99 = _tmp32 * _tmp88 - _tmp97 + _tmp98
    _tmp100 = _tmp40 * _tmp91
    _tmp101 = _tmp40 * _tmp93
    _tmp102 = _tmp100 - _tmp101
    _tmp103 = _tmp0 * _tmp84
    _tmp104 = _tmp103 * delta[0, 0]
    _tmp105 = -_tmp0 * _tmp88 + _tmp104
    _tmp106 = _tmp1 * _tmp84 * delta[0, 0]
    _tmp107 = -_tmp1 * _tmp88 + _tmp106
    _tmp108 = _tmp61 * _tmp63
    _tmp109 = _tmp0 * _tmp108
    _tmp110 = _tmp109 * delta[0, 0]
    _tmp111 = _tmp0 * _tmp73
    _tmp112 = _tmp111 * delta[0, 0]
    _tmp113 = _tmp110 - _tmp112
    _tmp114 = _tmp1 * _tmp108
    _tmp115 = _tmp114 * delta[0, 0]
    _tmp116 = _tmp1 * _tmp73
    _tmp117 = _tmp116 * delta[0, 0]
    _tmp118 = _tmp115 - _tmp117
    _tmp119 = delta[0, 0] ** 3
    _tmp120 = _tmp119 * _tmp84 - _tmp66 * _tmp87 - 2 * _tmp9
    _tmp121 = _tmp2 * _tmp71
    _tmp122 = _tmp35 * _tmp38
    _tmp123 = -_tmp108 * _tmp32 * delta[1, 0] + _tmp82 * delta[1, 0]
    _tmp124 = _tmp122 + _tmp123
    _tmp125 = _tmp33 - _tmp81 + _tmp82
    _tmp126 = _tmp53 * _tmp88
    _tmp127 = _tmp2 * _tmp93
    _tmp128 = _tmp62 * _tmp90
    _tmp129 = -_tmp32 * _tmp85
    _tmp130 = _tmp129 + _tmp14
    _tmp131 = _tmp92 - _tmp94
    _tmp132 = _tmp25 * delta[0, 0]
    _tmp133 = _tmp108 * _tmp119 - _tmp119 * _tmp73 - 4 * _tmp132
    _tmp134 = -_tmp122 + _tmp123
    _tmp135 = -_tmp41 + _tmp72 - _tmp74
    _tmp136 = _tmp129 - _tmp14
    _tmp137 = -_tmp100 + _tmp101
    _tmp138 = _tmp103 * delta[1, 0]
    _tmp139 = -_tmp12 * _tmp36 + _tmp36
    _tmp140 = _tmp139 * _tmp7
    _tmp141 = -_tmp0 * _tmp140 + _tmp138
    _tmp142 = delta[1, 0] ** 3
    _tmp143 = -_tmp1 * _tmp140 + _tmp142 * _tmp84 - 2 * _tmp46
    _tmp144 = _tmp1 * _tmp93
    _tmp145 = _tmp1 * _tmp91
    _tmp146 = _tmp140 * _tmp32
    _tmp147 = _tmp22 * _tmp70
    _tmp148 = _tmp53 * _tmp91
    _tmp149 = _tmp53 * _tmp93
    _tmp150 = -_tmp148 + _tmp149
    _tmp151 = -_tmp106 + _tmp140 * _tmp40 + _tmp9
    _tmp152 = 2 * _tmp132
    _tmp153 = -_tmp115 + _tmp117 + _tmp152
    _tmp154 = _tmp53 * _tmp71
    _tmp155 = _tmp53 * _tmp73
    _tmp156 = _tmp154 - _tmp155 - _tmp54
    _tmp157 = _tmp109 * delta[1, 0]
    _tmp158 = _tmp111 * delta[1, 0]
    _tmp159 = _tmp157 - _tmp158
    _tmp160 = _tmp108 * _tmp142 - _tmp142 * _tmp73 - 4 * _tmp76
    _tmp161 = _tmp148 - _tmp149
    _tmp162 = _tmp1 * _tmp96
    _tmp163 = _tmp140 * _tmp53 - _tmp162 + _tmp98
    _tmp164 = _tmp114 * delta[2, 0]
    _tmp165 = _tmp116 * delta[2, 0]
    _tmp166 = -_tmp164 + _tmp165 + _tmp60
    _tmp167 = -_tmp154 + _tmp155 + _tmp54
    _tmp168 = -_tmp139 * _tmp66 + _tmp86
    _tmp169 = _tmp78 - _tmp79
    _tmp170 = -_tmp12 * _tmp43 + _tmp43
    _tmp171 = _tmp170 * _tmp7
    _tmp172 = -_tmp1 * _tmp171 + _tmp162
    _tmp173 = delta[2, 0] ** 3
    _tmp174 = -_tmp0 * _tmp171 + _tmp173 * _tmp84 - 2 * _tmp98
    _tmp175 = _tmp0 * _tmp71
    _tmp176 = _tmp0 * _tmp93
    _tmp177 = _tmp0 * _tmp91
    _tmp178 = _tmp171 * _tmp40
    _tmp179 = -_tmp110 + _tmp112 + _tmp152
    _tmp180 = -_tmp104 + _tmp171 * _tmp32 + _tmp9
    _tmp181 = _tmp164 - _tmp165
    _tmp182 = _tmp108 * _tmp173 - _tmp173 * _tmp73 - 4 * _tmp59
    _tmp183 = -_tmp170 * _tmp66 + _tmp97
    _tmp184 = -_tmp157 + _tmp158 + _tmp77
    _tmp185 = -_tmp138 + _tmp171 * _tmp53 + _tmp46
    _tmp186 = _tmp65 - _tmp68
    _tmp187 = _tmp30 - 1
    _tmp188 = -_tmp10
    _tmp189 = -_tmp16
    _tmp190 = -_tmp47

    # Output terms
    _res = numpy.zeros(3)
    _res[0] = (
        -b_g[0, 0]
        - delta_dot[0, 0] * (_tmp29 + _tmp31)
        - delta_dot[1, 0] * (_tmp10 + _tmp15)
        - delta_dot[2, 0] * (_tmp16 + _tmp18)
        - omega_nominal[0, 0] * (_tmp24 + _tmp27 + 1)
        - omega_nominal[1, 0] * (_tmp42 + _tmp44)
        - omega_nominal[2, 0] * (_tmp34 - _tmp39)
        + z_gyro[0, 0]
    )
    _res[1] = (
        -b_g[1, 0]
        - delta_dot[0, 0] * (_tmp10 + _tmp45)
        - delta_dot[1, 0] * (_tmp31 + _tmp52)
        - delta_dot[2, 0] * (_tmp47 + _tmp48)
        - omega_nominal[0, 0] * (_tmp42 - _tmp44)
        - omega_nominal[1, 0] * (_tmp27 + _tmp50)
        - omega_nominal[2, 0] * (_tmp55 + _tmp57)
        + z_gyro[1, 0]
    )
    _res[2] = (
        -b_g[2, 0]
        - delta_dot[0, 0] * (_tmp16 + _tmp17)
        - delta_dot[1, 0] * (_tmp47 + _tmp58)
        - delta_dot[2, 0] * (_tmp29 + _tmp52 + 1)
        - omega_nominal[0, 0] * (_tmp34 + _tmp39)
        - omega_nominal[1, 0] * (_tmp55 - _tmp57)
        - omega_nominal[2, 0] * (_tmp24 + _tmp50)
        + z_gyro[2, 0]
    )
    _res_D_delta = numpy.zeros((3, 3))
    _res_D_delta[0, 0] = (
        -delta_dot[0, 0] * (_tmp105 + _tmp107)
        - delta_dot[1, 0] * (_tmp89 + _tmp95)
        - delta_dot[2, 0] * (_tmp102 + _tmp99)
        - omega_nominal[0, 0] * (_tmp113 + _tmp118)
        - omega_nominal[1, 0] * (_tmp80 + _tmp83)
        - omega_nominal[2, 0] * (_tmp69 + _tmp75)
    )
    _res_D_delta[1, 0] = (
        -delta_dot[0, 0] * (_tmp131 + _tmp89)
        - delta_dot[1, 0] * (_tmp105 + _tmp120)
        - delta_dot[2, 0] * (_tmp126 + _tmp127 - _tmp128 + _tmp130)
        - omega_nominal[0, 0] * (_tmp125 + _tmp80)
        - omega_nominal[1, 0] * (_tmp113 + _tmp133)
        - omega_nominal[2, 0] * (_tmp121 + _tmp124 - _tmp49 - _tmp67)
    )
    _res_D_delta[2, 0] = (
        -delta_dot[0, 0] * (_tmp137 + _tmp99)
        - delta_dot[1, 0] * (_tmp126 - _tmp127 + _tmp128 + _tmp136)
        - delta_dot[2, 0] * (_tmp107 + _tmp120)
        - omega_nominal[0, 0] * (_tmp135 + _tmp69)
        - omega_nominal[1, 0] * (-_tmp121 + _tmp134 + _tmp49 + _tmp67)
        - omega_nominal[2, 0] * (_tmp118 + _tmp133)
    )
    _res_D_delta[0, 1] = (
        -delta_dot[0, 0] * (_tmp141 + _tmp143)
        - delta_dot[1, 0] * (_tmp150 + _tmp151)
        - delta_dot[2, 0] * (_tmp136 - _tmp144 + _tmp145 + _tmp146)
        - omega_nominal[0, 0] * (_tmp159 + _tmp160)
        - omega_nominal[1, 0] * (_tmp153 + _tmp156)
        - omega_nominal[2, 0] * (_tmp116 + _tmp134 - _tmp147 + _tmp23)
    )
    _res_D_delta[1, 1] = (
        -delta_dot[0, 0] * (_tmp151 + _tmp161)
        - delta_dot[1, 0] * (_tmp141 + _tmp168)
        - delta_dot[2, 0] * (_tmp137 + _tmp163)
        - omega_nominal[0, 0] * (_tmp153 + _tmp167)
        - omega_nominal[1, 0] * (_tmp159 + _tmp169)
        - omega_nominal[2, 0] * (_tmp135 + _tmp166)
    )
    _res_D_delta[2, 1] = (
        -delta_dot[0, 0] * (_tmp130 + _tmp144 - _tmp145 + _tmp146)
        - delta_dot[1, 0] * (_tmp102 + _tmp163)
        - delta_dot[2, 0] * (_tmp143 + _tmp168)
        - omega_nominal[0, 0] * (-_tmp116 + _tmp124 + _tmp147 - _tmp23)
        - omega_nominal[1, 0] * (_tmp166 + _tmp75)
        - omega_nominal[2, 0] * (_tmp160 + _tmp169)
    )
    _res_D_delta[0, 2] = (
        -delta_dot[0, 0] * (_tmp172 + _tmp174)
        - delta_dot[1, 0] * (_tmp130 + _tmp176 - _tmp177 + _tmp178)
        - delta_dot[2, 0] * (_tmp161 + _tmp180)
        - omega_nominal[0, 0] * (_tmp181 + _tmp182)
        - omega_nominal[1, 0] * (-_tmp111 + _tmp124 + _tmp175 - _tmp26)
        - omega_nominal[2, 0] * (_tmp167 + _tmp179)
    )
    _res_D_delta[1, 2] = (
        -delta_dot[0, 0] * (_tmp136 - _tmp176 + _tmp177 + _tmp178)
        - delta_dot[1, 0] * (_tmp174 + _tmp183)
        - delta_dot[2, 0] * (_tmp185 + _tmp95)
        - omega_nominal[0, 0] * (_tmp111 + _tmp134 - _tmp175 + _tmp26)
        - omega_nominal[1, 0] * (_tmp182 + _tmp186)
        - omega_nominal[2, 0] * (_tmp184 + _tmp83)
    )
    _res_D_delta[2, 2] = (
        -delta_dot[0, 0] * (_tmp150 + _tmp180)
        - delta_dot[1, 0] * (_tmp131 + _tmp185)
        - delta_dot[2, 0] * (_tmp172 + _tmp183)
        - omega_nominal[0, 0] * (_tmp156 + _tmp179)
        - omega_nominal[1, 0] * (_tmp125 + _tmp184)
        - omega_nominal[2, 0] * (_tmp181 + _tmp186)
    )
    _res_D_delta_dot = numpy.zeros((3, 3))
    _res_D_delta_dot[0, 0] = _tmp187 + _tmp28
    _res_D_delta_dot[1, 0] = _tmp15 + _tmp188
    _res_D_delta_dot[2, 0] = _tmp18 + _tmp189
    _res_D_delta_dot[0, 1] = _tmp188 + _tmp45
    _res_D_delta_dot[1, 1] = _tmp187 + _tmp51
    _res_D_delta_dot[2, 1] = _tmp190 + _tmp48
    _res_D_delta_dot[0, 2] = _tmp17 + _tmp189
    _res_D_delta_dot[1, 2] = _tmp190 + _tmp58
    _res_D_delta_dot[2, 2] = _tmp28 + _tmp51 - 1
    _res_D_b_g = numpy.zeros((3, 3))
    _res_D_b_g[0, 0] = -1
    _res_D_b_g[1, 0] = 0
    _res_D_b_g[2, 0] = 0
    _res_D_b_g[0, 1] = 0
    _res_D_b_g[1, 1] = -1
    _res_D_b_g[2, 1] = 0
    _res_D_b_g[0, 2] = 0
    _res_D_b_g[1, 2] = 0
    _res_D_b_g[2, 2] = -1
    return _res, _res_D_delta, _res_D_delta_dot, _res_D_b_g
