"""
Auto-generated analytical Jacobians for radar-inertial odometry.

Generated by: derive_jacobians_symforce.py (using SymForce 0.10.1)
This file has NO dependency on SymForce — it uses only numpy and math.

Contains:
- radar_residual_with_jacobians(): Doppler residual + Jacobians w.r.t. v_world, delta, omega
- accel_residual_with_jacobians(): Accel residual + Jacobians w.r.t. a_world, delta, b_a
- Rot3: Lightweight quaternion wrapper matching SymForce convention [x, y, z, w]

Usage:
    from generated_jacobians import radar_residual_with_jacobians, accel_residual_with_jacobians, Rot3

    R_nom = Rot3(quat_xyzw)
    R_bs = Rot3(quat_xyzw)
    res, J_v, J_delta, J_omega = radar_residual_with_jacobians(
        v_world, R_nom, delta, omega, u_sensor, t_body_sensor, R_bs, v_meas, epsilon
    )
"""

import math
import typing as T
import numpy


class Rot3:
    """
    Lightweight quaternion wrapper matching SymForce Rot3 interface.

    Stores quaternion as [x, y, z, w] (Hamilton convention).
    Only provides the .data property needed by generated code.
    """
    __slots__ = ['data']

    def __init__(self, quat_xyzw):
        """
        Args:
            quat_xyzw: Quaternion as [x, y, z, w] array or list.
        """
        if hasattr(quat_xyzw, 'tolist'):
            self.data = quat_xyzw.tolist()
        else:
            self.data = list(quat_xyzw)

    @staticmethod
    def from_rotation_matrix(R):
        """
        Create Rot3 from a 3x3 rotation matrix.

        Uses Shepperd's method for numerical stability.
        Returns quaternion in [x, y, z, w] format.
        """
        trace = R[0, 0] + R[1, 1] + R[2, 2]
        if trace > 0:
            s = 0.5 / math.sqrt(trace + 1.0)
            w = 0.25 / s
            x = (R[2, 1] - R[1, 2]) * s
            y = (R[0, 2] - R[2, 0]) * s
            z = (R[1, 0] - R[0, 1]) * s
        elif R[0, 0] > R[1, 1] and R[0, 0] > R[2, 2]:
            s = 2.0 * math.sqrt(1.0 + R[0, 0] - R[1, 1] - R[2, 2])
            w = (R[2, 1] - R[1, 2]) / s
            x = 0.25 * s
            y = (R[0, 1] + R[1, 0]) / s
            z = (R[0, 2] + R[2, 0]) / s
        elif R[1, 1] > R[2, 2]:
            s = 2.0 * math.sqrt(1.0 + R[1, 1] - R[0, 0] - R[2, 2])
            w = (R[0, 2] - R[2, 0]) / s
            x = (R[0, 1] + R[1, 0]) / s
            y = 0.25 * s
            z = (R[1, 2] + R[2, 1]) / s
        else:
            s = 2.0 * math.sqrt(1.0 + R[2, 2] - R[0, 0] - R[1, 1])
            w = (R[1, 0] - R[0, 1]) / s
            x = (R[0, 2] + R[2, 0]) / s
            y = (R[1, 2] + R[2, 1]) / s
            z = 0.25 * s

        # Normalize
        norm = math.sqrt(x*x + y*y + z*z + w*w)
        return Rot3([x/norm, y/norm, z/norm, w/norm])



# ======================================================================
# RADAR DOPPLER RESIDUAL + JACOBIANS
# ======================================================================


# --- From: radar_residual_with_jacobians023.py ---

def radar_residual_with_jacobians(
    v_world, R_nominal, delta, omega, u_sensor, t_body_sensor, R_body_sensor, v_meas, epsilon
):
    # type: (numpy.ndarray, Rot3, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, Rot3, float, float) -> T.Tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray]
    """
    Radar Doppler residual.

    Forward model:
        R(t) = R_nominal * exp(delta)
        v_body = R^T * v_world
        v_ant = v_body + omega x t_body_sensor
        u_body = R_body_sensor * u_sensor
        v_pred = u_body . v_ant
        residual = v_meas - v_pred
        res_D_v_world: (1x3) jacobian of res (1) wrt arg v_world (3)
        res_D_delta: (1x3) jacobian of res (1) wrt arg delta (3)
        res_D_omega: (1x3) jacobian of res (1) wrt arg omega (3)
    """

    # Total ops: 513

    # Input arrays
    if v_world.shape == (3,):
        v_world = v_world.reshape((3, 1))
    elif v_world.shape != (3, 1):
        raise IndexError(
            "v_world is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                v_world.shape
            )
        )

    _R_nominal = R_nominal.data
    if delta.shape == (3,):
        delta = delta.reshape((3, 1))
    elif delta.shape != (3, 1):
        raise IndexError(
            "delta is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                delta.shape
            )
        )

    if omega.shape == (3,):
        omega = omega.reshape((3, 1))
    elif omega.shape != (3, 1):
        raise IndexError(
            "omega is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                omega.shape
            )
        )

    if u_sensor.shape == (3,):
        u_sensor = u_sensor.reshape((3, 1))
    elif u_sensor.shape != (3, 1):
        raise IndexError(
            "u_sensor is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                u_sensor.shape
            )
        )

    if t_body_sensor.shape == (3,):
        t_body_sensor = t_body_sensor.reshape((3, 1))
    elif t_body_sensor.shape != (3, 1):
        raise IndexError(
            "t_body_sensor is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                t_body_sensor.shape
            )
        )

    _R_body_sensor = R_body_sensor.data

    # Intermediate terms (156)
    _tmp0 = 2 * _R_body_sensor[1]
    _tmp1 = _R_body_sensor[2] * _tmp0
    _tmp2 = 2 * _R_body_sensor[0] * _R_body_sensor[3]
    _tmp3 = -2 * _R_body_sensor[0] ** 2
    _tmp4 = 1 - 2 * _R_body_sensor[2] ** 2
    _tmp5 = _R_body_sensor[0] * _tmp0
    _tmp6 = 2 * _R_body_sensor[2]
    _tmp7 = _R_body_sensor[3] * _tmp6
    _tmp8 = (
        u_sensor[0, 0] * (_tmp5 + _tmp7)
        + u_sensor[1, 0] * (_tmp3 + _tmp4)
        + u_sensor[2, 0] * (_tmp1 - _tmp2)
    )
    _tmp9 = delta[2, 0] ** 2
    _tmp10 = delta[1, 0] ** 2
    _tmp11 = delta[0, 0] ** 2
    _tmp12 = _tmp10 + _tmp11 + _tmp9 + epsilon**2
    _tmp13 = math.sqrt(_tmp12)
    _tmp14 = (1.0 / 2.0) * _tmp13
    _tmp15 = math.sin(_tmp14)
    _tmp16 = _tmp15 / _tmp13
    _tmp17 = _R_nominal[3] * _tmp16
    _tmp18 = _tmp17 * delta[1, 0]
    _tmp19 = _R_nominal[0] * _tmp16
    _tmp20 = _tmp19 * delta[2, 0]
    _tmp21 = _R_nominal[2] * _tmp16
    _tmp22 = _tmp21 * delta[0, 0]
    _tmp23 = math.cos(_tmp14)
    _tmp24 = _R_nominal[1] * _tmp23
    _tmp25 = _tmp18 - _tmp20 + _tmp22 + _tmp24
    _tmp26 = _tmp17 * delta[0, 0]
    _tmp27 = _R_nominal[1] * _tmp16
    _tmp28 = _tmp27 * delta[2, 0]
    _tmp29 = _tmp21 * delta[1, 0]
    _tmp30 = _R_nominal[0] * _tmp23
    _tmp31 = _tmp26 + _tmp28 - _tmp29 + _tmp30
    _tmp32 = 2 * _tmp31
    _tmp33 = _tmp25 * _tmp32
    _tmp34 = _tmp17 * delta[2, 0]
    _tmp35 = _tmp19 * delta[1, 0]
    _tmp36 = _tmp27 * delta[0, 0]
    _tmp37 = _R_nominal[2] * _tmp23
    _tmp38 = _tmp34 + _tmp35 - _tmp36 + _tmp37
    _tmp39 = _tmp19 * delta[0, 0]
    _tmp40 = _tmp27 * delta[1, 0]
    _tmp41 = _tmp21 * delta[2, 0]
    _tmp42 = _R_nominal[3] * _tmp23
    _tmp43 = -_tmp39 - _tmp40 - _tmp41 + _tmp42
    _tmp44 = 2 * _tmp43
    _tmp45 = _tmp38 * _tmp44
    _tmp46 = _tmp33 - _tmp45
    _tmp47 = 2 * _tmp25
    _tmp48 = _tmp38 * _tmp47
    _tmp49 = _tmp32 * _tmp43
    _tmp50 = _tmp48 + _tmp49
    _tmp51 = -2 * _tmp38**2
    _tmp52 = 1 - 2 * _tmp31**2
    _tmp53 = _tmp51 + _tmp52
    _tmp54 = _R_body_sensor[3] * _tmp0
    _tmp55 = _R_body_sensor[0] * _tmp6
    _tmp56 = -2 * _R_body_sensor[1] ** 2
    _tmp57 = (
        u_sensor[0, 0] * (_tmp4 + _tmp56)
        + u_sensor[1, 0] * (_tmp5 - _tmp7)
        + u_sensor[2, 0] * (_tmp54 + _tmp55)
    )
    _tmp58 = -2 * _tmp25**2
    _tmp59 = _tmp51 + _tmp58 + 1
    _tmp60 = _tmp33 + _tmp45
    _tmp61 = _tmp32 * _tmp38
    _tmp62 = _tmp25 * _tmp44
    _tmp63 = _tmp61 - _tmp62
    _tmp64 = _tmp52 + _tmp58
    _tmp65 = _tmp48 - _tmp49
    _tmp66 = _tmp61 + _tmp62
    _tmp67 = (
        u_sensor[0, 0] * (-_tmp54 + _tmp55)
        + u_sensor[1, 0] * (_tmp1 + _tmp2)
        + u_sensor[2, 0] * (_tmp3 + _tmp56 + 1)
    )
    _tmp68 = -_tmp19
    _tmp69 = _tmp15 / _tmp12 ** (3.0 / 2.0)
    _tmp70 = _R_nominal[2] * _tmp69
    _tmp71 = delta[0, 0] * delta[2, 0]
    _tmp72 = _tmp70 * _tmp71
    _tmp73 = (1.0 / 2.0) / _tmp12
    _tmp74 = _tmp30 * _tmp73
    _tmp75 = _R_nominal[0] * _tmp69
    _tmp76 = _tmp37 * _tmp73
    _tmp77 = _tmp71 * _tmp76
    _tmp78 = _R_nominal[1] * _tmp69
    _tmp79 = _tmp78 * delta[1, 0]
    _tmp80 = _tmp24 * _tmp73
    _tmp81 = delta[0, 0] * delta[1, 0]
    _tmp82 = _tmp79 * delta[0, 0] - _tmp80 * _tmp81
    _tmp83 = (
        -_tmp11 * _tmp74 + _tmp11 * _tmp75 - 1.0 / 2.0 * _tmp26 + _tmp68 + _tmp72 - _tmp77 + _tmp82
    )
    _tmp84 = 2 * _tmp38
    _tmp85 = _tmp83 * _tmp84
    _tmp86 = _tmp75 * _tmp81
    _tmp87 = -_tmp27
    _tmp88 = _tmp74 * _tmp81
    _tmp89 = _R_nominal[3] * _tmp69
    _tmp90 = _tmp42 * _tmp73
    _tmp91 = -_tmp71 * _tmp89 + _tmp71 * _tmp90
    _tmp92 = (
        _tmp11 * _tmp78 - _tmp11 * _tmp80 - 1.0 / 2.0 * _tmp22 - _tmp86 + _tmp87 + _tmp88 + _tmp91
    )
    _tmp93 = _tmp44 * _tmp92
    _tmp94 = -_tmp71 * _tmp74 + _tmp71 * _tmp75
    _tmp95 = -_tmp81 * _tmp89 + _tmp81 * _tmp90
    _tmp96 = -_tmp11 * _tmp70 + _tmp11 * _tmp76 + _tmp21 - 1.0 / 2.0 * _tmp36 + _tmp94 + _tmp95
    _tmp97 = _tmp71 * _tmp78
    _tmp98 = _tmp70 * _tmp81
    _tmp99 = _tmp76 * _tmp81
    _tmp100 = _tmp71 * _tmp80
    _tmp101 = (
        _tmp100
        - _tmp11 * _tmp89
        + _tmp11 * _tmp90
        + _tmp17
        - 1.0 / 2.0 * _tmp39
        - _tmp97
        + _tmp98
        - _tmp99
    )
    _tmp102 = _tmp101 * _tmp47 + _tmp32 * _tmp96
    _tmp103 = _tmp32 * _tmp83
    _tmp104 = _tmp101 * _tmp44
    _tmp105 = _tmp47 * _tmp92 + _tmp84 * _tmp96
    _tmp106 = 4 * _tmp38
    _tmp107 = -_tmp106 * _tmp92
    _tmp108 = 4 * _tmp31
    _tmp109 = -_tmp101 * _tmp108
    _tmp110 = 4 * _tmp25
    _tmp111 = -_tmp110 * _tmp96
    _tmp112 = _tmp47 * _tmp83
    _tmp113 = _tmp44 * _tmp96
    _tmp114 = _tmp101 * _tmp84 + _tmp32 * _tmp92
    _tmp115 = delta[1, 0] * delta[2, 0]
    _tmp116 = _tmp115 * _tmp70 - _tmp115 * _tmp76
    _tmp117 = (
        _tmp10 * _tmp78 - _tmp10 * _tmp80 + _tmp116 - 1.0 / 2.0 * _tmp18 + _tmp86 + _tmp87 - _tmp88
    )
    _tmp118 = _tmp117 * _tmp47
    _tmp119 = _tmp115 * _tmp75
    _tmp120 = _tmp115 * _tmp74
    _tmp121 = (
        -_tmp10 * _tmp89
        + _tmp10 * _tmp90
        + _tmp119
        - _tmp120
        + _tmp17
        - 1.0 / 2.0 * _tmp40
        - _tmp98
        + _tmp99
    )
    _tmp122 = _tmp121 * _tmp44
    _tmp123 = -_tmp115 * _tmp89 + _tmp115 * _tmp90
    _tmp124 = _tmp10 * _tmp74 - _tmp10 * _tmp75 + _tmp123 + _tmp19 - 1.0 / 2.0 * _tmp29 + _tmp82
    _tmp125 = -_tmp21
    _tmp126 = _tmp79 * delta[2, 0]
    _tmp127 = _tmp115 * _tmp80
    _tmp128 = (
        _tmp10 * _tmp70
        - _tmp10 * _tmp76
        + _tmp125
        - _tmp126
        + _tmp127
        - 1.0 / 2.0 * _tmp35
        + _tmp95
    )
    _tmp129 = _tmp124 * _tmp32 + _tmp128 * _tmp84
    _tmp130 = -_tmp110 * _tmp121
    _tmp131 = -_tmp108 * _tmp128
    _tmp132 = _tmp117 * _tmp32
    _tmp133 = _tmp128 * _tmp44
    _tmp134 = _tmp121 * _tmp84 + _tmp124 * _tmp47
    _tmp135 = -_tmp106 * _tmp124
    _tmp136 = _tmp117 * _tmp84
    _tmp137 = _tmp124 * _tmp44
    _tmp138 = _tmp121 * _tmp32 + _tmp128 * _tmp47
    _tmp139 = (
        -_tmp100
        - _tmp119
        + _tmp120
        + _tmp17
        - 1.0 / 2.0 * _tmp41
        - _tmp89 * _tmp9
        + _tmp9 * _tmp90
        + _tmp97
    )
    _tmp140 = 2 * _tmp139
    _tmp141 = _tmp140 * _tmp43
    _tmp142 = (
        2 * _tmp125
        + 2 * _tmp126
        - 2 * _tmp127
        - _tmp34
        + 2 * _tmp70 * _tmp9
        - 2 * _tmp76 * _tmp9
        + 2 * _tmp94
    )
    _tmp143 = _tmp142 * _tmp38
    _tmp144 = (
        _tmp123 - 1.0 / 2.0 * _tmp28 + _tmp68 - _tmp72 - _tmp74 * _tmp9 + _tmp75 * _tmp9 + _tmp77
    )
    _tmp145 = _tmp116 - 1.0 / 2.0 * _tmp20 + _tmp27 - _tmp78 * _tmp9 + _tmp80 * _tmp9 + _tmp91
    _tmp146 = _tmp144 * _tmp32 + _tmp145 * _tmp47
    _tmp147 = -_tmp110 * _tmp144
    _tmp148 = -_tmp106 * _tmp139
    _tmp149 = _tmp144 * _tmp44
    _tmp150 = _tmp142 * _tmp25
    _tmp151 = _tmp140 * _tmp31 + _tmp145 * _tmp84
    _tmp152 = _tmp145 * _tmp44
    _tmp153 = _tmp142 * _tmp31
    _tmp154 = _tmp140 * _tmp25 + _tmp144 * _tmp84
    _tmp155 = -_tmp108 * _tmp145

    # Output terms
    _res = numpy.zeros(1)
    _res[0] = (
        -_tmp57
        * (
            _tmp59 * v_world[0, 0]
            + _tmp60 * v_world[1, 0]
            + _tmp63 * v_world[2, 0]
            + omega[1, 0] * t_body_sensor[2, 0]
            - omega[2, 0] * t_body_sensor[1, 0]
        )
        - _tmp67
        * (
            _tmp64 * v_world[2, 0]
            + _tmp65 * v_world[1, 0]
            + _tmp66 * v_world[0, 0]
            + omega[0, 0] * t_body_sensor[1, 0]
            - omega[1, 0] * t_body_sensor[0, 0]
        )
        - _tmp8
        * (
            _tmp46 * v_world[0, 0]
            + _tmp50 * v_world[2, 0]
            + _tmp53 * v_world[1, 0]
            - omega[0, 0] * t_body_sensor[2, 0]
            + omega[2, 0] * t_body_sensor[0, 0]
        )
        + v_meas
    )
    _res_D_v_world = numpy.zeros(3)
    _res_D_v_world[0] = -_tmp46 * _tmp8 - _tmp57 * _tmp59 - _tmp66 * _tmp67
    _res_D_v_world[1] = -_tmp53 * _tmp8 - _tmp57 * _tmp60 - _tmp65 * _tmp67
    _res_D_v_world[2] = -_tmp50 * _tmp8 - _tmp57 * _tmp63 - _tmp64 * _tmp67
    _res_D_delta = numpy.zeros(3)
    _res_D_delta[0] = (
        -_tmp57
        * (
            v_world[0, 0] * (_tmp107 + _tmp111)
            + v_world[1, 0] * (_tmp102 + _tmp85 + _tmp93)
            + v_world[2, 0] * (-_tmp112 - _tmp113 + _tmp114)
        )
        - _tmp67
        * (
            v_world[0, 0] * (_tmp112 + _tmp113 + _tmp114)
            + v_world[1, 0] * (-_tmp103 - _tmp104 + _tmp105)
            + v_world[2, 0] * (_tmp109 + _tmp111)
        )
        - _tmp8
        * (
            v_world[0, 0] * (_tmp102 - _tmp85 - _tmp93)
            + v_world[1, 0] * (_tmp107 + _tmp109)
            + v_world[2, 0] * (_tmp103 + _tmp104 + _tmp105)
        )
    )
    _res_D_delta[1] = (
        -_tmp57
        * (
            v_world[0, 0] * (_tmp130 + _tmp135)
            + v_world[1, 0] * (_tmp136 + _tmp137 + _tmp138)
            + v_world[2, 0] * (-_tmp118 - _tmp122 + _tmp129)
        )
        - _tmp67
        * (
            v_world[0, 0] * (_tmp118 + _tmp122 + _tmp129)
            + v_world[1, 0] * (-_tmp132 - _tmp133 + _tmp134)
            + v_world[2, 0] * (_tmp130 + _tmp131)
        )
        - _tmp8
        * (
            v_world[0, 0] * (-_tmp136 - _tmp137 + _tmp138)
            + v_world[1, 0] * (_tmp131 + _tmp135)
            + v_world[2, 0] * (_tmp132 + _tmp133 + _tmp134)
        )
    )
    _res_D_delta[2] = (
        -_tmp57
        * (
            v_world[0, 0] * (_tmp147 + _tmp148)
            + v_world[1, 0] * (_tmp141 + _tmp143 + _tmp146)
            + v_world[2, 0] * (-_tmp149 - _tmp150 + _tmp151)
        )
        - _tmp67
        * (
            v_world[0, 0] * (_tmp149 + _tmp150 + _tmp151)
            + v_world[1, 0] * (-_tmp152 - _tmp153 + _tmp154)
            + v_world[2, 0] * (_tmp147 + _tmp155)
        )
        - _tmp8
        * (
            v_world[0, 0] * (-_tmp141 - _tmp143 + _tmp146)
            + v_world[1, 0] * (_tmp148 + _tmp155)
            + v_world[2, 0] * (_tmp152 + _tmp153 + _tmp154)
        )
    )
    _res_D_omega = numpy.zeros(3)
    _res_D_omega[0] = -_tmp67 * t_body_sensor[1, 0] + _tmp8 * t_body_sensor[2, 0]
    _res_D_omega[1] = -_tmp57 * t_body_sensor[2, 0] + _tmp67 * t_body_sensor[0, 0]
    _res_D_omega[2] = _tmp57 * t_body_sensor[1, 0] - _tmp8 * t_body_sensor[0, 0]
    return _res, _res_D_v_world, _res_D_delta, _res_D_omega


# ======================================================================
# ACCELEROMETER RESIDUAL + JACOBIANS
# ======================================================================


# --- From: accel_residual_with_jacobians025.py ---

def accel_residual_with_jacobians(a_world, R_nominal, delta, g_world, z_acc, b_a, epsilon):
    # type: (numpy.ndarray, Rot3, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, float) -> T.Tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray]
    """
    Accelerometer residual.

    Forward model:
        R(t) = R_nominal * exp(delta)
        predicted_specific_force = R^T * (a_world - g_world)
        residual = z_acc - predicted_specific_force - b_a
        res_D_a_world: (3x3) jacobian of res (3) wrt arg a_world (3)
        res_D_delta: (3x3) jacobian of res (3) wrt arg delta (3)
        res_D_b_a: (3x3) jacobian of res (3) wrt arg b_a (3)
    """

    # Total ops: 443

    # Input arrays
    if a_world.shape == (3,):
        a_world = a_world.reshape((3, 1))
    elif a_world.shape != (3, 1):
        raise IndexError(
            "a_world is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                a_world.shape
            )
        )

    _R_nominal = R_nominal.data
    if delta.shape == (3,):
        delta = delta.reshape((3, 1))
    elif delta.shape != (3, 1):
        raise IndexError(
            "delta is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                delta.shape
            )
        )

    if g_world.shape == (3,):
        g_world = g_world.reshape((3, 1))
    elif g_world.shape != (3, 1):
        raise IndexError(
            "g_world is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                g_world.shape
            )
        )

    if z_acc.shape == (3,):
        z_acc = z_acc.reshape((3, 1))
    elif z_acc.shape != (3, 1):
        raise IndexError(
            "z_acc is expected to have shape (3, 1) or (3,); instead had shape {}".format(
                z_acc.shape
            )
        )

    if b_a.shape == (3,):
        b_a = b_a.reshape((3, 1))
    elif b_a.shape != (3, 1):
        raise IndexError(
            "b_a is expected to have shape (3, 1) or (3,); instead had shape {}".format(b_a.shape)
        )

    # Intermediate terms (148)
    _tmp0 = a_world[1, 0] - g_world[1, 0]
    _tmp1 = delta[2, 0] ** 2
    _tmp2 = delta[1, 0] ** 2
    _tmp3 = delta[0, 0] ** 2
    _tmp4 = _tmp1 + _tmp2 + _tmp3 + epsilon**2
    _tmp5 = math.sqrt(_tmp4)
    _tmp6 = (1.0 / 2.0) * _tmp5
    _tmp7 = math.sin(_tmp6)
    _tmp8 = _tmp7 / _tmp5
    _tmp9 = _R_nominal[3] * _tmp8
    _tmp10 = _tmp9 * delta[1, 0]
    _tmp11 = _R_nominal[0] * _tmp8
    _tmp12 = _tmp11 * delta[2, 0]
    _tmp13 = _R_nominal[2] * _tmp8
    _tmp14 = _tmp13 * delta[0, 0]
    _tmp15 = math.cos(_tmp6)
    _tmp16 = _R_nominal[1] * _tmp15
    _tmp17 = _tmp10 - _tmp12 + _tmp14 + _tmp16
    _tmp18 = _tmp9 * delta[0, 0]
    _tmp19 = _R_nominal[1] * _tmp8
    _tmp20 = _tmp19 * delta[2, 0]
    _tmp21 = _tmp13 * delta[1, 0]
    _tmp22 = _R_nominal[0] * _tmp15
    _tmp23 = _tmp18 + _tmp20 - _tmp21 + _tmp22
    _tmp24 = 2 * _tmp23
    _tmp25 = _tmp17 * _tmp24
    _tmp26 = _tmp9 * delta[2, 0]
    _tmp27 = _tmp11 * delta[1, 0]
    _tmp28 = _tmp19 * delta[0, 0]
    _tmp29 = _R_nominal[2] * _tmp15
    _tmp30 = _tmp26 + _tmp27 - _tmp28 + _tmp29
    _tmp31 = _tmp11 * delta[0, 0]
    _tmp32 = _tmp19 * delta[1, 0]
    _tmp33 = _tmp13 * delta[2, 0]
    _tmp34 = _R_nominal[3] * _tmp15
    _tmp35 = -2 * _tmp31 - 2 * _tmp32 - 2 * _tmp33 + 2 * _tmp34
    _tmp36 = _tmp30 * _tmp35
    _tmp37 = 2 * _tmp17**2
    _tmp38 = -_tmp37
    _tmp39 = 2 * _tmp30**2
    _tmp40 = 1 - _tmp39
    _tmp41 = a_world[0, 0] - g_world[0, 0]
    _tmp42 = a_world[2, 0] - g_world[2, 0]
    _tmp43 = 2 * _tmp30
    _tmp44 = _tmp23 * _tmp43
    _tmp45 = _tmp17 * _tmp35
    _tmp46 = -_tmp45
    _tmp47 = -_tmp36
    _tmp48 = 2 * _tmp23**2
    _tmp49 = -_tmp48
    _tmp50 = _tmp17 * _tmp43
    _tmp51 = _tmp23 * _tmp35
    _tmp52 = -_tmp51
    _tmp53 = _tmp39 - 1
    _tmp54 = -_tmp25
    _tmp55 = -_tmp44
    _tmp56 = -_tmp50
    _tmp57 = _tmp7 / _tmp4 ** (3.0 / 2.0)
    _tmp58 = _R_nominal[2] * _tmp57
    _tmp59 = _tmp58 * delta[2, 0]
    _tmp60 = _tmp59 * delta[0, 0]
    _tmp61 = -_tmp11
    _tmp62 = (1.0 / 2.0) / _tmp4
    _tmp63 = _tmp22 * _tmp62
    _tmp64 = _tmp3 * _tmp57
    _tmp65 = _tmp29 * _tmp62
    _tmp66 = delta[0, 0] * delta[2, 0]
    _tmp67 = _tmp65 * _tmp66
    _tmp68 = _R_nominal[1] * _tmp57
    _tmp69 = _tmp68 * delta[0, 0]
    _tmp70 = delta[0, 0] * delta[1, 0]
    _tmp71 = _tmp16 * _tmp62
    _tmp72 = _tmp69 * delta[1, 0] - _tmp70 * _tmp71
    _tmp73 = (
        _R_nominal[0] * _tmp64
        - 1.0 / 2.0 * _tmp18
        - _tmp3 * _tmp63
        + _tmp60
        + _tmp61
        - _tmp67
        + _tmp72
    )
    _tmp74 = 2 * _tmp17
    _tmp75 = _tmp73 * _tmp74
    _tmp76 = _R_nominal[0] * _tmp57
    _tmp77 = _tmp76 * delta[2, 0]
    _tmp78 = -_tmp63 * _tmp66 + _tmp77 * delta[0, 0]
    _tmp79 = _R_nominal[3] * _tmp57
    _tmp80 = _tmp34 * _tmp62
    _tmp81 = -_tmp70 * _tmp79 + _tmp70 * _tmp80
    _tmp82 = (
        -_R_nominal[2] * _tmp64 + _tmp13 - 1.0 / 2.0 * _tmp28 + _tmp3 * _tmp65 + _tmp78 + _tmp81
    )
    _tmp83 = _tmp35 * _tmp82
    _tmp84 = -_tmp19
    _tmp85 = _tmp70 * _tmp76
    _tmp86 = _tmp63 * _tmp70
    _tmp87 = -_tmp66 * _tmp79 + _tmp66 * _tmp80
    _tmp88 = (
        _R_nominal[1] * _tmp64
        - 1.0 / 2.0 * _tmp14
        - _tmp3 * _tmp71
        + _tmp84
        - _tmp85
        + _tmp86
        + _tmp87
    )
    _tmp89 = _tmp69 * delta[2, 0]
    _tmp90 = _tmp58 * _tmp70
    _tmp91 = _tmp65 * _tmp70
    _tmp92 = _tmp66 * _tmp71
    _tmp93 = (
        -_R_nominal[3] * _tmp64
        + _tmp3 * _tmp80
        - 1.0 / 2.0 * _tmp31
        - _tmp89
        + _tmp9
        + _tmp90
        - _tmp91
        + _tmp92
    )
    _tmp94 = _tmp24 * _tmp88 + _tmp43 * _tmp93
    _tmp95 = 4 * _tmp17
    _tmp96 = -_tmp82 * _tmp95
    _tmp97 = 4 * _tmp30
    _tmp98 = -_tmp88 * _tmp97
    _tmp99 = _tmp43 * _tmp73
    _tmp100 = _tmp35 * _tmp88
    _tmp101 = _tmp24 * _tmp82 + _tmp74 * _tmp93
    _tmp102 = 4 * _tmp23
    _tmp103 = -_tmp102 * _tmp93
    _tmp104 = _tmp24 * _tmp73
    _tmp105 = _tmp35 * _tmp93
    _tmp106 = _tmp43 * _tmp82 + _tmp74 * _tmp88
    _tmp107 = _tmp77 * delta[1, 0]
    _tmp108 = _tmp2 * _tmp62
    _tmp109 = delta[1, 0] * delta[2, 0]
    _tmp110 = _tmp109 * _tmp63
    _tmp111 = (
        _tmp107
        + _tmp108 * _tmp34
        - _tmp110
        - _tmp2 * _tmp79
        - 1.0 / 2.0 * _tmp32
        + _tmp9
        - _tmp90
        + _tmp91
    )
    _tmp112 = -_tmp111 * _tmp95
    _tmp113 = -_tmp109 * _tmp79 + _tmp109 * _tmp80
    _tmp114 = _tmp11 + _tmp113 + _tmp2 * _tmp63 - _tmp2 * _tmp76 - 1.0 / 2.0 * _tmp21 + _tmp72
    _tmp115 = -_tmp114 * _tmp97
    _tmp116 = -_tmp109 * _tmp65 + _tmp59 * delta[1, 0]
    _tmp117 = (
        -1.0 / 2.0 * _tmp10 - _tmp108 * _tmp16 + _tmp116 + _tmp2 * _tmp68 + _tmp84 + _tmp85 - _tmp86
    )
    _tmp118 = _tmp117 * _tmp43
    _tmp119 = _tmp114 * _tmp35
    _tmp120 = -_tmp13
    _tmp121 = _tmp109 * _tmp68
    _tmp122 = _tmp109 * _tmp71
    _tmp123 = (
        -_tmp108 * _tmp29
        + _tmp120
        - _tmp121
        + _tmp122
        + _tmp2 * _tmp58
        - 1.0 / 2.0 * _tmp27
        + _tmp81
    )
    _tmp124 = _tmp111 * _tmp24 + _tmp123 * _tmp74
    _tmp125 = _tmp117 * _tmp74
    _tmp126 = _tmp111 * _tmp35
    _tmp127 = _tmp114 * _tmp24 + _tmp123 * _tmp43
    _tmp128 = -_tmp102 * _tmp123
    _tmp129 = _tmp117 * _tmp24
    _tmp130 = _tmp123 * _tmp35
    _tmp131 = _tmp111 * _tmp43 + _tmp114 * _tmp74
    _tmp132 = (
        -_tmp1 * _tmp79
        + _tmp1 * _tmp80
        - _tmp107
        + _tmp110
        - 1.0 / 2.0 * _tmp33
        + _tmp89
        + _tmp9
        - _tmp92
    )
    _tmp133 = _tmp132 * _tmp35
    _tmp134 = (
        _tmp1 * _tmp58 - _tmp1 * _tmp65 + _tmp120 + _tmp121 - _tmp122 - 1.0 / 2.0 * _tmp26 + _tmp78
    )
    _tmp135 = _tmp134 * _tmp43
    _tmp136 = (
        -_tmp1 * _tmp63 + _tmp1 * _tmp76 + _tmp113 - 1.0 / 2.0 * _tmp20 - _tmp60 + _tmp61 + _tmp67
    )
    _tmp137 = -_tmp1 * _tmp68 + _tmp1 * _tmp71 + _tmp116 - 1.0 / 2.0 * _tmp12 + _tmp19 + _tmp87
    _tmp138 = _tmp136 * _tmp24 + _tmp137 * _tmp74
    _tmp139 = -_tmp136 * _tmp95
    _tmp140 = -_tmp132 * _tmp97
    _tmp141 = _tmp136 * _tmp35
    _tmp142 = _tmp134 * _tmp74
    _tmp143 = _tmp132 * _tmp24 + _tmp137 * _tmp43
    _tmp144 = _tmp137 * _tmp35
    _tmp145 = _tmp134 * _tmp24
    _tmp146 = _tmp132 * _tmp74 + _tmp136 * _tmp43
    _tmp147 = -_tmp102 * _tmp137

    # Output terms
    _res = numpy.zeros(3)
    _res[0] = (
        -_tmp0 * (_tmp25 + _tmp36)
        - _tmp41 * (_tmp38 + _tmp40)
        - _tmp42 * (_tmp44 + _tmp46)
        - b_a[0, 0]
        + z_acc[0, 0]
    )
    _res[1] = (
        -_tmp0 * (_tmp40 + _tmp49)
        - _tmp41 * (_tmp25 + _tmp47)
        - _tmp42 * (_tmp50 + _tmp51)
        - b_a[1, 0]
        + z_acc[1, 0]
    )
    _res[2] = (
        -_tmp0 * (_tmp50 + _tmp52)
        - _tmp41 * (_tmp44 + _tmp45)
        - _tmp42 * (_tmp38 + _tmp49 + 1)
        - b_a[2, 0]
        + z_acc[2, 0]
    )
    _res_D_a_world = numpy.zeros((3, 3))
    _res_D_a_world[0, 0] = _tmp37 + _tmp53
    _res_D_a_world[1, 0] = _tmp36 + _tmp54
    _res_D_a_world[2, 0] = _tmp46 + _tmp55
    _res_D_a_world[0, 1] = _tmp47 + _tmp54
    _res_D_a_world[1, 1] = _tmp48 + _tmp53
    _res_D_a_world[2, 1] = _tmp51 + _tmp56
    _res_D_a_world[0, 2] = _tmp45 + _tmp55
    _res_D_a_world[1, 2] = _tmp52 + _tmp56
    _res_D_a_world[2, 2] = _tmp37 + _tmp48 - 1
    _res_D_delta = numpy.zeros((3, 3))
    _res_D_delta[0, 0] = (
        -_tmp0 * (_tmp100 + _tmp101 + _tmp99)
        - _tmp41 * (_tmp96 + _tmp98)
        - _tmp42 * (-_tmp75 - _tmp83 + _tmp94)
    )
    _res_D_delta[1, 0] = (
        -_tmp0 * (_tmp103 + _tmp98)
        - _tmp41 * (-_tmp100 + _tmp101 - _tmp99)
        - _tmp42 * (_tmp104 + _tmp105 + _tmp106)
    )
    _res_D_delta[2, 0] = (
        -_tmp0 * (-_tmp104 - _tmp105 + _tmp106)
        - _tmp41 * (_tmp75 + _tmp83 + _tmp94)
        - _tmp42 * (_tmp103 + _tmp96)
    )
    _res_D_delta[0, 1] = (
        -_tmp0 * (_tmp118 + _tmp119 + _tmp124)
        - _tmp41 * (_tmp112 + _tmp115)
        - _tmp42 * (-_tmp125 - _tmp126 + _tmp127)
    )
    _res_D_delta[1, 1] = (
        -_tmp0 * (_tmp115 + _tmp128)
        - _tmp41 * (-_tmp118 - _tmp119 + _tmp124)
        - _tmp42 * (_tmp129 + _tmp130 + _tmp131)
    )
    _res_D_delta[2, 1] = (
        -_tmp0 * (-_tmp129 - _tmp130 + _tmp131)
        - _tmp41 * (_tmp125 + _tmp126 + _tmp127)
        - _tmp42 * (_tmp112 + _tmp128)
    )
    _res_D_delta[0, 2] = (
        -_tmp0 * (_tmp133 + _tmp135 + _tmp138)
        - _tmp41 * (_tmp139 + _tmp140)
        - _tmp42 * (-_tmp141 - _tmp142 + _tmp143)
    )
    _res_D_delta[1, 2] = (
        -_tmp0 * (_tmp140 + _tmp147)
        - _tmp41 * (-_tmp133 - _tmp135 + _tmp138)
        - _tmp42 * (_tmp144 + _tmp145 + _tmp146)
    )
    _res_D_delta[2, 2] = (
        -_tmp0 * (-_tmp144 - _tmp145 + _tmp146)
        - _tmp41 * (_tmp141 + _tmp142 + _tmp143)
        - _tmp42 * (_tmp139 + _tmp147)
    )
    _res_D_b_a = numpy.zeros((3, 3))
    _res_D_b_a[0, 0] = -1
    _res_D_b_a[1, 0] = 0
    _res_D_b_a[2, 0] = 0
    _res_D_b_a[0, 1] = 0
    _res_D_b_a[1, 1] = -1
    _res_D_b_a[2, 1] = 0
    _res_D_b_a[0, 2] = 0
    _res_D_b_a[1, 2] = 0
    _res_D_b_a[2, 2] = -1
    return _res, _res_D_a_world, _res_D_delta, _res_D_b_a
